#
#  For more information, please see: http://software.sci.utah.edu
# 
#  The MIT License
# 
#  Copyright (c) 2004 Scientific Computing and Imaging Institute,
#  University of Utah.
# 
#  License for the specific language governing rights and limitations under
#  Permission is hereby granted, free of charge, to any person obtaining a
#  copy of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom the
#  Software is furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
#

# Makefile.vc
# written by Chris Moulding 8/99

###########################  EDIT HERE  ###########################

## the name of the .dll and/or .exe to be built by linking the OBJS
DLLNAME = Dataflow
EXENAME = 

## the files to be compiled. .odll and .oexe extensions indicate
## that the file will be linked into a dll or exe binary, respectively.
OBJS = Comm\MessageBase.odll\
       Constraints\AngleConstraint.odll Constraints\BaseConstraint.odll\
	   Constraints\BaseVariable.odll Constraints\CenterConstraint.odll\
	   Constraints\ConstraintSolver.odll Constraints\DistanceConstraint.odll\
	   Constraints\LineConstraint.odll Constraints\PlaneConstraint.odll\
	   Constraints\ProjectConstraint.odll Constraints\Pythagorasconstraint.odll\
	   Constraints\RatioConstraint.odll Constraints\SegmentConstraint.odll\
	   Constraints\VarCore.odll\
	   Dataflow\Connection.odll Dataflow\ModuleHelper.odll Dataflow\Network.odll\
	   Dataflow\Port.odll Dataflow\Module.odll Dataflow\NetworkEditor.odll\
	   Dataflow\PackageDB.odll\
	   Datatypes\BooleanPort.odll Datatypes\ColorMapPort.odll\
	   Datatypes\ColumnMatrixPort.odll\
	   Datatypes\GeometryPort.odll Datatypes\HexMeshPort.odll\
	   Datatypes\IntervalPort.odll Datatypes\MatrixPort.odll\
	   Datatypes\MeshPort.odll Datatypes\ScalarFieldPort.odll\
	   Datatypes\ScaledBoxWidgetData.odll Datatypes\ScaledBoxWidgetDataPort.odll\
	   Datatypes\SoundPort.odll Datatypes\SurfacePort.odll\
	   Datatypes\VectorFieldPort.odll Datatypes\VoidStarPort.odll\
	   Datatypes\cMatrixPort.odll Datatypes\cVectorPort.odll\
	   share\DllEntry.odll\
	   Widgets\ArrowWidget.odll Widgets\BaseWidget.odll Widgets\BoxWidget.odll\
	   Widgets\CriticalPointWidget.odll Widgets\CrosshairWidget.odll\
	   Widgets\FrameWidget.odll Widgets\GaugeWidget.odll Widgets\LightWidget.odll\
	   Widgets\PathWidget.odll Widgets\PointWidget.odll Widgets\RingWidget.odll\
	   Widgets\ScaledBoxWidget.odll Widgets\ScaledFrameWidget.odll\
	   Widgets\ViewWidget.odll

## override, or append to, the default compiler and/or linker flags with these
CF   = -DBUILD_PSECORE
LF   = 

## add to the default include paths
INCS = 

## add to the default list of libraries to link against
LIBS = Core$(APPENDIX).lib

###################################################################

!include <$(TOP)\src\scripts\Makefile.vc.master>