#!/bin/csh
#
#.......................................................................
# pscp
# pscp <num Processors>  <login@Machine>:<remote dir> < localDirectory>
# You must be able to ssh onto the remote machine without a password
# or it won't work.
#.......................................................................
#echo $argv
#
#------------------
# unalias commands
unalias ssh
unalias rm
unalias cd

#------------------
# error checking
if ($#argv != 3) then
  echo " pscp < number of Processors>  <login@Remote Machine>:<remote dir> < local dir>"
  exit(0)
endif

set nproc         = $argv[1]
set localDir      = $argv[3]
set string        = $argv[2]
set remote_machine = `echo $string |cut -d\@ -f2 | cut -d\: -f1`
set user_test      = `echo $string |cut  -s -d\@ -f1`

if ( $user_test == ""   ) then
  set user_test = $USER
endif

setenv LOGIN              $user_test@$remote_machine
setenv REMOTEDIR_TMP      `echo $string |cut -d\: -f2`
setenv LOCALDIR           $localDir
setenv REMOTEDIR          $REMOTEDIR_TMP

echo "login:       $LOGIN"
echo "nprocessors: $nproc"
echo "localDir:    $localDir"
echo "remoteDir:   $REMOTEDIR"

#------------------
# Bulletproofing
echo "Bullet proof tests"

echo "  Test: does the local folder ($localDir) exist"
if ( ! -e $localDir ) then
  echo " ERROR: local directory $localDir doesn't exist"
  exit(1)
endif

echo "  Test: passwordless access."
set test = `ssh -x $LOGIN "echo 'password_access_works'"`
if ( $test != "password_access_works" ) then
  echo " ERROR:  passwordless access is not working."
  echo "         You must be able to login into the $remote_machine without a password for this script to work"
  exit(1)
endif

echo "  Test: Do we know about the remote operating system"
set OS = `ssh -x $LOGIN uname`
if ( $OS != "Linux" && $OS != "IRIX64" ) then
  echo " ERROR: there is no pscp_driver for this operating system: $OS"
  exit(1)
endif
echo "_____________________________________"
#------------------
# Now do the work
echo "Now removing stamp directory"
/bin/rm -rf Stamp
mkdir $localDir
cd $localDir

/usr/bin/time -p gmake -f /usr/gapps/uintah/scripts/pscp_pull_driver -j $nproc

cd ..
exit(1)
