#! /bin/bash

THELIB=TabProps

source ../HelperBuildScripts/setupEnv.sh

rm -f CMakeCache.txt
rm -rf ${INSTALL_HERE}/*

cmake                                       \
  -DTabProps_PREPROCESSOR=OFF               \
  -DTabProps_UTILS=OFF                      \
  -DTabProps_ENABLE_TESTING=OFF             \
  -DTabProps_ENABLE_IO=ON                   \
  -DBOOST_INCLUDEDIR=$BOOST_LOC/include     \
  -DBOOST_LIBRARYDIR=$BOOST_LOC/lib         \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE}    \
  -DCMAKE_C_COMPILER=$CC                    \
  -DCMAKE_CXX_COMPILER=$CXX                 \
  -DCMAKE_CXX_FLAGS="-fPIC"                 \
  .

if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "Updating permissions on ${INSTALL_HERE}..."
  echo ""
  chmod -R go+rX ${INSTALL_HERE}/..
fi
