#! /bin/bash

THELIB=TabProps

source ../HelperBuildScripts/setupEnv.sh

rm -rf CMakeCache.txt CMakeFiles *.cmake
rm -rf ${INSTALL_HERE}/*

if test "$BUILD_CUDA" = "yes"; then
  FLAGS="-DENABLE_THREADS=OFF
         -DENABLE_CUDA=ON
         -DDISABLE_INTROSPECTION=ON
         -DCUDA_ARCHITECTURE_MINIMUM=\"3.5\" 
         -DCUDA_HOST_COMPILER=/opt/gcc/4.9.3/bin/g++"
fi

cmake_cmd=\
"
  cmake
    $FLAGS
    -DTabProps_PREPROCESSOR=OFF
    -DTabProps_UTILS=OFF
    -DTabProps_ENABLE_TESTING=OFF
    -DTabProps_ENABLE_IO=ON
    -DBOOST_INCLUDEDIR=$BOOST_LOC/include
    -DBOOST_LIBRARYDIR=$BOOST_LOC/lib
    -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE}
    -DCMAKE_C_COMPILER=$CC
    -DCMAKE_CXX_COMPILER=$CXX
    -DCMAKE_CXX_FLAGS=\"-fPIC\"
    ../TabProps
"

echo ""
echo "Running CMAKE command:"
echo $cmake_cmd
echo ""

eval $cmake_cmd


if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "Updating permissions on ${INSTALL_HERE}..."
  echo ""
  chmod -R go+rX ${INSTALL_HERE}/..
fi
