#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTest import runSusTests

TESTS = [   ("methane_explicit", "methane_explicit_table.ups", 1.1, "chem_meth.bin"), \
            ("methane_explicit_8patch", "methane_explicit_table_8patch.ups", 8, "chem_meth.bin")
    	]

def chemfile (test):
    return test[3]

def chemfileCallback (test, susdir, inputsdir, compare_root, algo, mode, max_parallelism):
  symlink("%s/inputs/ARCHES/input.dtd" % (susdir), "input.dtd")
  symlink("%s/inputs/ARCHES/%s" % (susdir, chemfile(test)), "chem.bin")

exit(runSusTests(argv, TESTS, "arches", chemfileCallback))
