#!/usr/local/bin/python

from os import symlink
from sys import argv,exit,platform
from helpers.runSusTests import runSusTests

TESTS = [   ("methane_explicit", "methane_explicit_table.ups", "", 1.1, "chem_meth"), \
            ("methane_explicit_8patch", "methane_explicit_table_8patch.ups", "", 8, "chem_meth")
    	]

def chemfile (test):
    return test[4]

def chemfileCallback (test, susdir, inputsdir, compare_root, algo, mode, max_parallelism):
  symlink("%s/input.dtd" % (inputsdir), "input.dtd")
  cfile = chemfile(test)
  if platform[0:5] == "linux":
      cfile = cfile + ".linux.bin"
  else:
      cfile = cfile + ".bin"
  symlink("%s/%s" % (inputsdir, cfile), "chem.bin")

exit(runSusTests(argv, TESTS, "arches", chemfileCallback))

