#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTest import runSusTests

TESTS = [   ("advect", "advect.ups", 1),	\
            ("hotBlob2mat", "hotBlob2mat.ups", 1)     \
    	]

exit(runSusTests(argv, TESTS, "ice"))
