#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTests import runSusTests, inputs_root
from helpers.modUPS import modUPS

hotBlob_AMR_3L_ups = modUPS("%s/ICE" % inputs_root(), \
                           "hotBlob_AMR.ups", \
                           ["<max_levels>3</max_levels>",\
                            "<lattice_refinement_ratio> [[5,5,1],[2,2,1]]  </lattice_refinement_ratio>",\
                            "<filebase>AMR_HotBlob_3L.uda</filebase>"])

UNUSED = [  ]

TESTS = [   ("advect", "advect.ups", 1, "Linux"),	\
            ("rieman_sm", "rieman_sm.ups", 1, "ALL"),     \
            ("hotBlob2mat", "hotBlob2mat.ups", 1, "Linux"),     \
            ("hotBlob2mat_sym", "hotBlob2mat_sym.ups", 1, "Linux"),     \
            ("impHotBlob", "impHotBlob.ups", 1, "ALL"),     \
            ("hotBlob8patch", "hotBlob2mat8patch.ups", 8, "Linux"),     \
            ("advect2matAMR", "advect2matAMR.ups", 1, "ALL"),     \
            ("hotBlob_AMR", "hotBlob_AMR.ups", 4, "Linux"), \
            ("hotBlob_AMR_3L", hotBlob_AMR_3L_ups, 4, "Linux"),  \
            ("impAdvectAMR", "impAdvectAMR.ups", 1.1, "Linux")
    	]

exit(runSusTests(argv, TESTS, "ICE"))
