#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTests import runSusTests

TESTS = [   ("disks2mat4patch4proc", "disks2mat4patch.ups", 4), \
	    ("disks_fracture", "disks_fracture.ups", 1), \
	    ("periodic_disks", "periodic_disks.ups", 6),	\
	    ("heatcond2mat", "heatcond2mat.ups", 1), \
    	    ("inclined_plane_sphere", "inclined_plane_sphere.ups", 1), \
	    ("const_test_cmr", "const_test_cmr.ups", 1), \
	    ("const_test_hypo", "const_test_hypo.ups", 1), \
	    ("const_test_nh", "const_test_nh.ups", 1), \
	    ("const_test_nhp", "const_test_nhp.ups", 1), \
	    ("const_test_vs", "const_test_vs.ups", 1), \
    	]

exit(runSusTests(argv, TESTS, "mpm"))
