#!/usr/local/bin/perl

$, = ' ';		# set output field separator
$\ = "\n";		# set output record separator

@files = @ARGV;

print <<'EOD';
\documentclass{report}
\raggedbottom

\pagestyle{headings}

\begin{document}


\chapter{Uintah ICE Function descriptions}

\section{Introduction}

The following contains includes a list of the functions that are currently being
used in Uintah-ICE CFD code.

\section{Index of Routines}

EOD
print (`date`);
#______________________________________________________________________
# Extract index of routines
#_______________________________________________________________________*/

print '\begin{description}';
while (<>) {
    chop;	# strip record separator
    if (/Function:/) {
       ($rest, $function)= split (":  ", $_, 0);
       ($function,$rest) = split(" ",$function);
       #__________________________________
       #  change "_" characters to "\_"
       #  so latex doesn't barf
       #___________________________________*/
       $function =~s/_/\\\_/g;

      print "\\item[$function]";
      push (@functions, $function);
    }
}

# Sort the function list.
@function = sort(@function);
print '\end{description}';
print ' ';

print '{\tiny';
print '\hrule';
print '\newpage';
#______________________________________________________________________
# Extract documentation from the source code: output LaTex code
#_______________________________________________________________________*/
@ARGV = @files;
while (<>)
{
  #__________________________________
  # Find the keyword Function: and 
  # Extract the function name   
  #___________________________________*/
  /Function:/ && do
  {
    print '\hrule';
    print '';
    print ''; chop;
    ($rest, $function)= split (":  ", $_, 0);
    ($function,$rest) = split (" ",$function);
    #__________________________________
    #  change "_" characters to "\_"
    #  so latex doesn't barf
    #___________________________________*/
    $function =~s/_/\\\_/g;
    #__________________________________
    #   TESTING
    #___________________________________*/
#     $filename = ">".substr($function,0).".tex";
#     open(OUT,$filename);
#     select (OUT);
    
    #__________________________________
    #   TESTING
    #___________________________________*/    
    print "\\subsection*{$function $rest \}";
    
    next;
  };

  #__________________________________
  # Find the keyword "Filename: and 
  # start extracting code   
  #___________________________________
  /Filename:/ && do
  {
    print '\begin{verbatim}' if $echo == 0;
    $echo = 1;
    print &Getline0();
    next;
  };
  #__________________________________
  #   When you find the keyword "STOP_DOC"
  #   then stop extracting code
  #___________________________________

  /STOP_DOC/ && do
  {
    print '\end{verbatim}' if $echo == 1;
    print '\hrule' if $echo == 1;
    $echo = 0;
    print '\newpage';
    next;
  };

  next if ! $echo;
  #__________________________________
  #   Printout each line if echo == 1
  #___________________________________
  /./ && do
  {
    chop;
    print substr($_, 0) if $echo == 1;
    next;
  };

  chop; print;
}

print <<'EOD';
}
\end{document}
EOD

#______________________________________________________________________
#   Some function thingy.
#______________________________________________________________________ 

sub Getline0 {
    if ($getline_ok = (($_ = <>) ne '')) {
	chop;	# strip record separator
    }
    $_;
}
