#!/bin/bash

TEST_UDADIR=$1
COMPARE_UDADIR=$2
ABS_TOL=$3  # Absolute tolerance
REL_TOL=$4  # Relative tolerance

if [ ! -d "$TEST_UDADIR" ]; then
  echo "$TEST_UDADIR doesn't exist"
  exit 1
fi  
if [ ! -d "$COMPARE_UDADIR" ]; then
  echo "$COMPARE_UDADIR doesn't exist"
  exit 1
fi

# choose the first dat file to compare number of lines later
ls -1 $TEST_UDADIR/*.dat
retval=$?
echo
if [ $retval != "0" ]; then
    # $TEST_UDADIR has no dat files
    ls -1 $COMPARE_UDADIR/*.dat
    retval=$?
    echo
    if [ $retval != "0" ]; then
	# $COMPARE_UDADIR has no dat files either
	echo "No dat files to compare"
        exit -1
    else
        # $COMPARE_UDADIR does have at least one dat file so
        # there is no excuse for $TEST_UDADIR for not having any.
        echo "The new uda directory has no dat files, but the old one does"
        exit 1
    fi
fi

WD=`pwd`
cd $TEST_UDADIR
dats=`ls -1 *.dat`
testdat=`ls -1 *.dat | head -n 1`
cd $WD

#echo "compare_dat_files.pl $ABS_TOL $REL_TOL $TEST_UDADIR/ $COMPARE_UDADIR/ $dats"

compare_dat_files.pl $ABS_TOL $REL_TOL $TEST_UDADIR/ $COMPARE_UDADIR/ $dats

retval=$?

newcount="0"
oldcount="0"

if [ $retval = "0" ]; then
    newcount=`grep -c '\0' $TEST_UDADIR/$testdat`
    oldcount=`grep -c '\0' $COMPARE_UDADIR/$testdat`

    if [ $newcount != $oldcount ]; then
        cat <<EOF
There is a discrepancy in the line count of the dat files.
There are $newcount lines in the new $testdat and
          $oldcount lines in the old $testdat.
This could simply be a result of a change to the timestep size.
EOF
    fi
fi

exit $retval

