/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit AtomicCounter.scc instead 
 */

#ifndef SCI_THREAD_ATOMICCOUNTER_H
#define SCI_THREAD_ATOMICCOUNTER_H 1

/*
 * Provides a simple atomic counter.  This will work just like an
 * integer, but guarantees atomicty of the ++ and -- operators.
 * Despite their convenience, you do not want to make a large number
 * of these objects.  See also <b>WorkQueue</b>.
 */

#include "Mutex.h"

class AtomicCounter {
    const char* name;
    Mutex lock;
    int value;
public:
    AtomicCounter(const char* name) ;
    AtomicCounter(const char* name, int value) ;
    ~AtomicCounter() ;
    operator int() const ;
    AtomicCounter& operator++() ;
    int operator++(int) ;
    AtomicCounter& operator--() ;
    int operator--(int) ;
};

#endif
