/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit Parallel.scc instead 
 */

#ifndef SCI_THREAD_PARALLEL_H
#define SCI_THREAD_PARALLEL_H 1

/*
 * Helper class to make instantiating threads to perform a parallel
 * task easier.
 */

#include "ParallelBase.h"

template<class T> class Parallel  : public ParallelBase {
    T* obj;
    void (T::*pmf)(int);
protected:
    virtual void run(int proc) ;
public:
    Parallel(T* obj, void (T::*pmf)(int)) ;
    ~Parallel() ;
};

template<class T> void Parallel< T>::run(int proc) {
    (obj->*pmf)(proc);
}

template<class T> Parallel< T>::Parallel(T* obj, void (T::*pmf)(int)) : obj(obj), pmf(pmf) {}

template<class T> Parallel< T>::~Parallel() {}

#endif
