/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit RealtimeThread.scc instead 
 */

#ifndef SCI_THREAD_REALTIMETHREAD_H
#define SCI_THREAD_REALTIMETHREAD_H 1

/*
 * Extended threads with realtime capabilities.  These realtime
 * capabilities may not be available on all machines, but the
 * functionality will be approximated on those that do not.
 *
 * <p>On multiprocessor machines, the realtime threads typically
 * take control of a single CPU.  On uniprocessor machines, they
 * can consume a large percentage of the processing resources
 * if the interval is too small.
 *
 * <p>Until this thread calls <i>frameSchedule</i>, this thread
 * behaves exactly like any other thread.
 */
class Thread;


class RealtimeThread {
    int interval;
public:
    void frameSchedule(int interval, RealtimeThread* idleThread);
    void frameReady();
    void frameYield();
    bool quantumExceeded;
    int frameInterval() ;
};

#endif
