/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit ThreadTopology.scc instead 
 */

#ifndef SCI_THREAD_THREADTOPOLOGY_H
#define SCI_THREAD_THREADTOPOLOGY_H 1

/*
 * Simple interface for defining a complex topology for inter-thread
 * communication.  For a set of <tt>nthreads</tt> threads, the
 * topology is constructed by connecting one thread to another thread
 * with an optional <tt>weight</tt>.  Weights have arbitrary value,
 * and their relative magnitude expresses the importantance of keeping
 * two threads near each other when mapping the threads to physical
 * processors.
 */


class ThreadTopology {
public:
    ThreadTopology(int nthreads) ;
    ~ThreadTopology() ;
    void connect(int from, int to, unsigned int weight=10) ;
};

#endif
