/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit ThreadEvent.scc instead 
 */

#ifndef SCI_THREAD_THREADEVENT_H
#define SCI_THREAD_THREADEVENT_H 1

/*
 * Simple struct for specifying thread events that can be sent from
 * the thread scheduler to the <b>ThreadListener</b>s.
 */


#include "Thread.h"
struct ThreadEvent {
    enum EventType {
	THREAD_START,
	THREAD_DONE
    };
    const char* threadName;
    SysClock timestamp;
};

#endif
