#!/bin/csh -f

#__________________________________
# This wrapper scripts just calls the RMCRT 
# 3 times for each direction
#
#  Usage:  RMCRT_wrapper  -o out.8.cmp -uda RMCRT_test_1L_8.uda
#__________________________________

# parse the input arguments and extract $out and $uda
while (1)
  switch($1:q)  # $1 is first argument
  case -o:
    shift
    set out = $1
    breaksw;
  case -uda:
    shift
    set uda = $1
    break
  endsw
  shift
end

set out_x = `echo $out`_x
set out_y = `echo $out`_y
set out_z = `echo $out`_z

echo "Now running RMCRT scripts in each direction (X,Y,Z) ($out, $uda)"
`RMCRT.m -o "$out_x" -uda $uda -pDir 1`
`RMCRT.m -o "$out_y" -uda $uda -pDir 2`
`RMCRT.m -o "$out_z" -uda $uda -pDir 3`

paste $out_x $out_y $out_z > $out

exit(0)
