#!/bin/csh
#__________________________________
# plotMinMax  <variable name>  <uda>
#  This script plots the min and max of variable as a function of time
#  It currently works on 2 levels
#__________________________________


if( $#argv != 2) then
  echo " plotMinMax <variable name >  < uda directory>"
  exit (1)
endif 

set var = $argv[1]      #variable name
set f = $argv[2]        # uda directory

echo "Executing puda -varsummary "
puda -varsummary $f | grep -A 12 $var | grep -A 5 "Level: 0" | grep min | cut -d " " -f 3 | cut -d "[" -f1 >& L-0_min
puda -varsummary $f | grep -A 12 $var | grep -A 5 "Level: 0" | grep max | cut -d " " -f 3 | cut -d "[" -f1 >& L-0_max

puda -varsummary $f | grep -A 12 $var | grep -A 5 "Level: 1" | grep min | cut -d " " -f 3 | cut -d "[" -f1 >& L-1_min
puda -varsummary $f | grep -A 12 $var | grep -A 5 "Level: 1" | grep max | cut -d " " -f 3 | cut -d "[" -f1 >& L-1_max

puda -timesteps $f | tr ":" " " |sed '1D' >& timestep

paste -d " " timestep L-0_min L-0_max L-1_min L-1_max > data

#__________________________________
# generate the gnuplot script
echo "Generating the gnuplot script"
echo "" > gp
#__________________________________
# if making a hardcopy
echo "Generating the postscript file plotStats.ps"
/bin/rm gp
cat > gp << fin
set terminal x11 1
#set terminal postscript color solid "Times-Roman" 9
#set output "$f.ps"
fin



cat >> gp << fin
set multiplot
set size 1.0,0.5 # for three plots
set origin 0.0,0.5
set autoscale
#set xdata time
set grid xtics ytics

set y2tics
set ylabel "$var"
set xlabel 'time'

plot 'data' using 2:3  t 'L-0 min' with lines,\
     'data' using 2:4  t 'L-0 max' with lines
          
set origin 0.0,0.0
plot 'data' using 2:5  t 'L-1 min' with lines,\
     'data' using 2:6  t 'L-1 max' with lines

set nomultiplot
pause -1 "Hit return to exit"
fin

#__________________________________
# plot it up
gnuplot gp


#__________________________________
# clean up
rm -f gp data

exit()
