lappend auto_path $sci_root/Modules/ASCI
lappend auto_path $sci_root/Modules/CFD
lappend auto_path $sci_root/Modules/FEM
lappend auto_path $sci_root/Modules/Fields
lappend auto_path $sci_root/Modules/HP
lappend auto_path $sci_root/Modules/Image
lappend auto_path $sci_root/Modules/Matrix
lappend auto_path $sci_root/Modules/Mesh
lappend auto_path $sci_root/Modules/Readers
lappend auto_path $sci_root/Modules/Salmon
lappend auto_path $sci_root/Modules/Sound
lappend auto_path $sci_root/Modules/Surface
lappend auto_path $sci_root/Modules/Visualization
lappend auto_path $sci_root/Modules/Writers
lappend auto_path $sci_root/Widgets
lappend auto_path $sci_root/TCL
lappend auto_path $sci_root/Devices
lappend auto_path $sci_root/Modules/Matrix
