#! /bin/bash

THELIB=SpatialOps

source ../HelperBuildScripts/setupEnv.sh

rm -f CMakeCache.txt
rm -rf ${INSTALL_HERE}/*

cmake \
  -DENABLE_TESTS=OFF \
  -DENABLE_THREADS=ON \
  -DNTHREADS=1 \
  -DENABLE_EXAMPLES=OFF \
  -DBOOST_ROOT=$BOOST_LOC \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE} \
  -DCMAKE_C_COMPILER=$CC \
  -DCMAKE_CXX_COMPILER=$CXX \
  -DCMAKE_CXX_FLAGS="-fPIC" \
  .

if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "SpatialOps: Updating installation permissions for ${INSTALL_HERE}..."
  chmod -R go+rX ${INSTALL_HERE}
fi

