
CFILES         += main2.c \
                  input.c \
                  plot_particles.c \
                  nist_fire.c \
                  interpolate_vel_CC_to_FC.c \
                  Source_Sinks/momentum.c \
                  Source_Sinks/energy.c \
 
ICE_DIR         = ../..

include ../../Makefile
