XML = [
    '<Uintah_specification>                                        \n', ...
    ' <Meta>                                                       \n', ...
    '  <title>CC PhaseField scalability test</title>               \n', ...
    ' </Meta>                                                      \n', ...
    ' <SimulationComponent type="phasefield" />                    \n', ...
    ' <Scheduler type="%s" />                                      \n', ...
    ' <Time>                                                       \n', ...
    '  <maxTime>1000.0</maxTime>                                   \n', ...
    '  <initTime>0.0</initTime>                                    \n', ...
    '  <delt_min>0.01</delt_min>                                   \n', ...
    '  <delt_max>1.</delt_max>                                     \n', ...
    '  <timestep_multiplier>1.</timestep_multiplier>               \n', ...
    ' </Time>                                                      \n', ...
    ' <DataArchiver>                                               \n', ...
    '  <filebase>%s.uda</filebase>                                 \n', ...
    '  <outputTimestepInterval>0</outputTimestepInterval>          \n', ...
    ' </DataArchiver>                                              \n', ...
    ' <PhaseField>                                                 \n', ...
    '  <delt>0.075</delt>                                          \n', ...
    '  <alpha>1.</alpha>                                           \n', ...
    '  <R0>5.</R0>                                                 \n', ...
    '  <Delta>0.65</Delta>                                         \n', ...
    '  <epsilon>0.05</epsilon>                                     \n', ...
    '  <dimension>3</dimension>                                    \n', ...
    ' </PhaseField>                                                \n', ...
    ' <Grid>                                                       \n', ...
    '  <Level>                                                     \n', ...
    '   <Box label="1">                                            \n', ...
    '    <lower>[%d, %d, %d]</lower>                               \n', ...
    '    <upper>[%d, %d, %d]</upper>                               \n', ...
    '    <patches>[%d, %d, %d]</patches>                           \n', ...
    '   </Box>                                                     \n', ...
    '   <spacing>[1., 1., 1.]</spacing>                            \n', ...
    '  </Level>                                                    \n', ...
    ' </Grid>                                                      \n', ...
    '</Uintah_specification>                                       \n'];

core_patch_size = 300;

scheduler = {'MPI','DynamicMPI','Unified' };
for s=1:3
    for log8_cores=0:2
        for load=0:log8_cores
            cores = 8^log8_cores;
            patches = [2, 3, 4]*2^load;
            lower = -patches/2 * core_patch_size;
            upper = patches/2 * core_patch_size;
            patches = [2, 3, 4]*2^log8_cores;
            
            filename = sprintf('cc_weak_scalability_3d_%s_%d_%d', scheduler{s}, cores, load);
            xml = sprintf(XML,scheduler{s},filename,lower(1),lower(2),lower(3),upper(1),upper(2),upper(3),patches(1),patches(2),patches(3));
            
            fid = fopen ( [filename '.ups'], 'wt' );
            fprintf(fid, xml);
            fclose(fid);
        end
    end
end

