/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sdm_spa_actors_scirun_SCIRunUtils */

#ifndef _Included_org_sdm_spa_actors_scirun_SCIRunUtils
#define _Included_org_sdm_spa_actors_scirun_SCIRunUtils
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: libLoader */
/* Inaccessible static: scirunStarted */
/*
 * Class:     org_sdm_spa_actors_scirun_SCIRunUtils
 * Method:    getScirun
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_sdm_spa_actors_scirun_SCIRunUtils_getScirun
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_sdm_spa_actors_scirun_SCIRunUtils
 * Method:    exitAllSCIRunThreads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sdm_spa_actors_scirun_SCIRunUtils_exitAllSCIRunThreads
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
