itcl_class CardioWave_DiscreteMultiDomain_DMDCreateElectrodes {
    inherit Module
    constructor {config} {
        set name DMDCreateElectrodes
        set_defaults
    }

    method set_defaults {} {
    }

    method ui {} {
        set w .ui[modname]
        if {[winfo exists $w]} {
            return
        }
        toplevel $w
        label $w.row1 -text "This GUI was auto-generated by the Component Wizard."
        label $w.row2 -text {edit the file "/Users/jeroen/projects/scirun/branch/src/Packages/CardioWave/Dataflow/GUI/DMDCreateElectrodes.tcl" to modify it.}
        pack $w.row1 $w.row2 -side top -padx 10 -pady 10

        makeSciButtonPanel $w $w $this
        moveToCursor $w
    }
}


