#!/bin/bash

TEST_UDADIR=$1
COMPARE_UDADIR=$2
SUS_DIR=$3
ABS_TOL=$4  # Absolute tolerance
REL_TOL=$5  # Relative tolerance

inputs_differ=0
echo
echo "*************************"
echo "Comparing $TEST_UDADIR with $COMPARE_UDADIR"
echo "*************************"
echo
echo "Checking input files"
echo

if [ -s $TEST_UDADIR/input.xml.orig ]; then
  echo "comparing input.xml.orig"
  sdiff -Ws $TEST_UDADIR/input.xml.orig $COMPARE_UDADIR/input.xml.orig
else
  echo "comparing input.xml"
  sdiff -Ws $TEST_UDADIR/input.xml $COMPARE_UDADIR/input.xml
fi

if [ $? != "0" ]; then
    echo
    echo "  Input files differ."
    inputs_differ=1
else
    echo "  Input files are the same."
fi

failed="0"
echo
echo "Comparing dat files"
echo "======================================"
echo
echo "compare_dats $TEST_UDADIR $COMPARE_UDADIR $ABS_TOL $REL_TOL"

compare_dats $TEST_UDADIR $COMPARE_UDADIR $ABS_TOL $REL_TOL
compare_dats_retval=$?
if [ $compare_dats_retval = "1" ]; then
    echo 
    echo "*** dat comparison tests failed ***"
    failed="1"
elif [ $compare_dats_retval = "-1" ]; then
    failed="-1"
fi


echo
echo "Comparing udas"
echo "======================================"
echo
echo "$SUS_DIR/compare_uda -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL $TEST_UDADIR $COMPARE_UDADIR"

$SUS_DIR/compare_uda -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL $TEST_UDADIR $COMPARE_UDADIR
uda_retval=$?

if [ $uda_retval != "0" ]; then
    echo 
    echo "*** uda comparison tests failed ***"
    failed="1"
fi

echo
echo "Comparing checkpoints"
echo "======================================"
if [[ -d "$TEST_UDADIR/checkpoints" &&  -d "$COMPARE_UDADIR/checkpoints" ]]; then
  echo
  echo "$SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints"

  $SUS_DIR/compare_uda -skip_unknown_types -abs_tolerance $ABS_TOL -rel_tolerance $REL_TOL -skip_unknown_types $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints
  chp_retval=$?

  if [ $chp_retval != "0" ]; then
      echo 
      echo "*** checkpoint comparison tests failed ***"
      failed="1"
  fi

  if [ $failed != "0" ]; then
      if [ $inputs_differ = "1" ]; then
          exit 5;
      fi
      exit $failed
  fi

  if [ $inputs_differ = "1" ]; then
      exit 10;
  fi
else
  echo "       WARNING: The checkpoint directory was not present in either the goldstandard or the test"
  echo "                No comparison performed"
fi

exit 0

