#!/bin/csh
#-------------------------------------------------
#    removeBraces <filename> 
#  This removes the '[' ']' from a file
#-------------------------------------------------
set files = ($argv)

echo "files: " $files
if ($#argv == 0) then
  echo " removeBraces <file1 file2 file3......>"
  exit(0)
endif

foreach X ( $files[*]:q )
  sed 's/\[//g' $X | sed 's/\]//g' >$X.tmp
  mv $X.tmp $X
end

exit
