#!/bin/bash
#______________________________________________________________________
# This script does the following:
#   - create a configure_command file
#   - execute the configure_command file
#   - Compiles the code 
#     If the code fails to compile the logs are created
#   - Adds information to the web log
#______________________________________________________________________

export OS
mode=$1 # dbg or opt
MACHINE=`hostname`

#__________________________________
# construct the configure_command file

if [ "$OS" = "Linux" ]; then
  
  
  DBG_CONFIGURE="    --enable-debug \\
      --enable-64bit \\
      --enable-sci-malloc \\
      --enable-scinew-line-numbers \\"
  
  OPT_CONFIGURE="    --enable-64bit \\
      --enable-assertion-level=0 \\
     '--enable-optimize=-O3 -mfpmath=sse' \\"
  #
  #  machine specific variables
  if [ "$MACHINE" == "rt" ]; then    
    COMMON="      --with-boost=/usr  \\
     --enable-wasatch_3p \\
     USE_WASATCH=yes \\"
  
    ENV="     CC=gcc \\
     CXX=g++ \\
     F77=gfortran"
  fi
  
  if [ "$MACHINE" == "blaze" ]; then  
    export PETSC_ARCH=linux-gnu-amd64
    COMMON="      --with-mpi=/usr/lib/openmpi \\
       --with-petsc=/usr/ \\
       --with-hypre=/usr/ \\
       --with-boost=/usr/ \\
       --enable-wasatch_3p \\
       USE_WASATCH=yes \\"

    ENV="      CC=gcc \\
       CXX=g++ \\
       F77=gfortran"
  fi
  
  if [ "$MACHINE" == "coconino" ]; then
    COMMON="      --with-mpi=/usr/local/openmpi \\
       --with-petsc=/usr/local/petsc \\
       --with-hypre=/usr/local/hypre \\
       --with-boost=/usr/local/boost \\
       --enable-wasatch_3p \\
       USE_WASATCH=yes \\"

    ENV="      CC=gcc \\
       CXX=g++ \\
       F77=gfortran"   
      
elif [ "$OS" = "Darwin" ]; then
  export PETSC_ARCH=darwin9.4.0-c-real-opt
  COMMON="    --enable-package='Uintah Teem' \\
       --with-petsc=/usr/sci/projects/Uintah/Thirdparty/1.0.0/Darwin/PPC-9.4.0/gcc-4.0.1-openmpi-32bit \\
       --with-hypre=/usr/sci/projects/Uintah/Thirdparty/1.0.0/Darwin/PPC-9.4.0/gcc-4.0.1-openmpi-32bit \\
       --with-mpi=/usr/local/openmpi \\"
  DBG_CONFIGURE="$COMMON $DBG_CONFIGURE"
  OPT_CONFIGURE="$COMMON '--enable-optimize=-mcpu=7450 -O2 -fsigned-char -maltivec -mabi=altivec -mpowerpc-gfxopt' $OPT_CONFIGURE"
fi


#__________________________________
echo "#!/bin/csh" > configure_command
echo "../../src/configure --enable-package=Uintah \\" >> configure_command
 
if [ "$mode" = "dbg" ]; then
  echo "$DBG_CONFIGURE" >> configure_command
  echo "$COMMON" >> configure_command
  echo "$ENV" >> configure_command
elif [ "$mode" = "opt" ]; then
  echo "$OPT_CONFIGURE" >> configure_command
  echo "$COMMON" >> configure_command
  echo "$ENV" >> configure_command
fi

chmod a+x configure_command
retval="0"

#__________________________________
echo "" >> $HTMLLOG
echo "Compiling" >> $HTMLLOG
echo "==================================" >> $HTMLLOG
echo "" >> $HTMLLOG
echo "Starting configure on `date`" >> $HTMLLOG
echo "  with command" >> $HTMLLOG
cat configure_command >> $HTMLLOG
echo "" >> $HTMLLOG


#__________________________________
# determing which "make" to use
which make
retval=$?
which gmake
retval1=$?

if [ $retval -eq 0 ]; then
  MAKE=make
elif [ $retval1 -eq 0 ]; then
  MAKE=gmake
fi

#__________________________________
#  run configure
rm -f "$BUILDROOT"/${mode}/configure.log
./configure_command > "$BUILDROOT"/${mode}/configure.log 2>&1
retval=$?

chgrp $COMMON_GROUP *
chmod g+rwX * 


#__________________________________
# configure:  failed
if [ $retval -ne 0 ]; then
  echo "Configure failed:" >> $HTMLLOG
  cat "${BUILDROOT}"/"${mode}"/configure.log >> $HTMLLOG

  echo "*** Configure failed with code $retval"
  echo ""
# echo "Showing configure log:"
# cat "${BUILDROOT}/${mode}/configure.log"

  cd "${BUILD_DIR}"
  if [ ! -d "configure-${mode}.lock" ]; then
   # failed ${mode} configure, set a lock
   ln -s "$BUILDROOT" "configure-${mode}.lock"
  fi
  exit 1
fi

#__________________________________
# configure:  Passed
echo "Configure successful"

if [ -d "${BUILD_DIR}/configure-${mode}.lock" ]; then
  # configured successfully - remove old configure lock 
  rm "${BUILD_DIR}/configure-${mode}.lock"
fi


#__________________________________
#  start compiling
echo "Starting build on `date`:" >> $HTMLLOG

cd "${BUILDROOT}/${mode}/build"
    
rm -f "../make.log" "../make_results.log"

$MAKE -k -j$MAKE_PARALLELISM >> ../make.log 2>&1


retval=$?
if [ $retval != "0" ]; then
  # try it again -- it may not go all the way the first time
  echo "Failed first compile, try again"
  $MAKE -k -j$MAKE_PARALLELISM >> ../make2.log 2>&1
  retval=$?
fi

if [ $retval != "0" ]; then
  # try it again -- it may not go all the way the first time
  echo "Failed second compile, try again (storing make errors)"
  $MAKE -k -j$MAKE_PARALLELISM > ../make3.log 2>&1
  retval=$?
fi

if [ $retval != "0" ]; then
  # failed 3 times
  if [[ -x "${BUILDROOT}/${mode}/build/StandAlone/sus" && -x "${BUILDROOT}/${mode}/build/StandAlone/compare_uda" ]]; then
    # sus compiled
    echo "__________________________________"
    echo "*** Make failed, but sus & compare_uda compiled successfully"
    echo "  Build errors log:"
    echo "    ${BUILDROOT}/${mode}/make3.log"
    echo "  Full build log:"
    echo "    ${BUILDROOT}/${mode}/make.log"
    echo ""

    # Add compilation errors to webpage
    cat ../make_results.log >> "$HTMLLOG"

    set a lock for this build
    if [ ! -d "${BUILD_DIR}/make-${mode}.lock" ]; then
      ln -s "$BUILDROOT" "${BUILD_DIR}/make-${mode}.lock"
    fi
    
  else  
    #sus didn't compile
    exit 1
  fi
fi

#__________________________________
# compile successfully remove make lock
if [ -d "${BUILD_DIR}/make-${mode}.lock" ]; then
  rm "${BUILD_DIR}/make-${mode}.lock"
fi

echo "Sus compiled successfully"
echo "Sus compiled successfully" >> $HTMLLOG
exit 0
