#! /bin/bash

#
# This script updates, builds, and installs the 3P Wasatch libraries... 
#

echo
echo "Building Wasatch 3P libraries."

source HelperBuildScripts/checkEnv.sh

export GIT_SSL_NO_VERIFY=true 

for dir in SpatialOps ExprLib TabProps RadProps NSCBC
do

  echo "--- Building $dir ---"
  echo

  if ! test -d "$dir"; then
    echo "WARNING: W3P source directory $dir does not appear to be 'git'ed yet. Downloading it now:"
    echo
    git clone --depth 1 http://gitlab.multiscale.utah.edu/common/$dir.git
  fi

  echo "----- Updating GIT files for $dir ---"
  echo

  cd $dir
  git pull

  if test "$?" != "0"; then
    echo "Error, 'git pull' failed for $dir!"
    exit
  fi

  echo
  echo "----- Installing $dir -----"
  echo
  cd ../$dir-build

  ./doit

  if test $? != 0; then
      exit -1
  fi

  cd ..

done
