#!/bin/sh
echo " ICE Version 2.0"
echo " INDEX OF FUNCTIONS"
echo ""
#______________________________________________________________________
# Extract index
#_______________________________________________________________________
awk '
    #______________________________
    # Find the keyworkd function
    # and extract the name of the function
    #______________________________    
    /Function:/ { print substr($0, 1, 500)}
    
' $*
#______________________________________________________________________
# Extract the information from the top to the bottom of parameter list
#_______________________________________________________________________
awk '
    #______________________________
    # Find the keyword "Function:"
    # and extract the name of the function
    #______________________________  
    /Function:/ { 
         print ""; 
         print "";
         print "";
         print "------------------------------------------------------------------------";
         print "" substr($0, 1, 500);
         print "------------------------------------------------------------------------"; 
         print "";
       }   
       
    #______________________________
    # Find the keyworkd "Function:"
    # and extract the text between
    # Function: and "}"
    #______________________________           
    /Function:/ { echo = 1; getline }
    /{/         { echo = 0}
    echo == 1 {print substr($0, 1, 500) }
   
' $*
#______________________________________________________________________
# Extract the detailed information from inside of the code
#_______________________________________________________________________
awk '
    #______________________________
    # Find the keyword "Function:"
    # and extract the name of the function
    #______________________________  
    /Function:/ { 
         print ""; 
         print "";
         print "";
         print "------------------------------------------------------------------------";
         print "" substr($0, 1, 500);
         print "------------------------------------------------------------------------"; 
         print "";
       } 
    #______________________________
    # Find the keywork "START_DOC"
    # and extract the text between
    # "START_DOC" and "STOP_DOC"
    #______________________________ 
    /START_DOC/ { echo = 2; getline }
    /STOP_DOC/  { echo = 0}
    echo == 2 {print "" substr($0, 1, 500) }
' $*


