#! /bin/sh
#
#.......................................................................
# pscp2 <num Processors> <transfer entire uda (y/n)> < remove remote directory> < localDirectory> <login@Machine>:<remote dir>
# You must be able to ssh onto the remote machine without a password
# or it won't work.
#.......................................................................
#echo $argv
#
#------------------
# unalias commands
unalias -a ssh
unalias -a rm
unalias -a cd

#------------------
# error checking
if test "$#" -ne 5; then
  echo ""
  echo "Usage: pscp2 < number of Processors> <transfer entire uda (y/n) > < remove remote directory (y/n) > < local dir to be copied> <login@Remote Machine>:<remote dir>"
  echo ""
  exit 1
fi

if test ${SSH+set}; then
   echo ""
   echo "Note: Using this ssh from environment var SSH: $SSH"
   echo ""
else
   SSH=ssh
fi

# Need /usr/bin/which as the shell which doesn't give us the full path...
if test ! -x /usr/bin/which; then
  echo ""
  echo "Error:  Can't find /usr/bin/which...  Goodbye."
  echo ""
  exit 1
fi

#pscp2fulldir=`/usr/bin/which $0`
pscp2fulldir=`readlink -f $0`
pscp2dir=`dirname $pscp2fulldir`

nproc=$1
transferWholeUda=$2
rmDir=$3
localDir=$4

if test `echo $localDir | cut -c1` != "/"; then
  # Not absolute path... fix it.
  localDir=`pwd`/$4
fi

string=$5
remote_machine=`echo $string |cut -d\@ -f2 | cut -d\: -f1`
user_test=`echo $string |cut  -s -d\@ -f1`

if test "$user_test" == ""; then
  user_test=$USER
fi

export LOGIN=$user_test@$remote_machine
export REMOTEDIR_PARENT=`echo $string |cut -d\: -f2`
export REMOTEDIR=$REMOTEDIR_PARENT/`basename $localDir`
export PSCP_FILES=/tmp/pscp_files_`basename $localDir`_`whoami`

echo "_____________________________________"
echo "Inputs:"
echo "	login:                 $LOGIN"
echo "	# processors:          $nproc"
echo "	transfer whole uda:    $transferWholeUda"
echo "	localDir:              $localDir"
echo "	remoteDir:             $REMOTEDIR"
echo "	remove the remote directory?: " $rmDir
echo "	PSCP_FILES:            $PSCP_FILES"
echo "	pscp2dir:              $pscp2dir"
echo "_____________________________________"
echo ""
#------------------
# Bulletproofing
echo "Bullet proof tests:"

validateTransferredFilesDir()
{
  if test -d "$STAMP_DIR"; then
    echo ""
    echo "  WARNING: It appears that these files were in the process of being transferred"
    echo "           but were interrupted.  The list of files that were already transferred can"
    echo "           be found in the $STAMP_DIR/stamp directory."
    echo ""
    echo "  MORE WARNING: It is possible, though unlikely, that some of the files listed"
    echo "                as transferred were not successfully sent.  Please validate your"
    echo "                UDA once all files have been transferred."
    echo ""
    echo "  Do you wish to continue (with the transfer of the remaining files)? (y/n)"
    echo "     (If not, manually remove the following directory and run this script again:"
    echo "           $STAMP_DIR)"
    echo ""
    echo -n " Please answer y/n: "
    read answer
    echo ""
    if test "$answer" != "y"; then
      echo "Goodbye."
      echo ""
      exit 1
    fi
    if test "$rmDir" == "y" -o "$rmDir" == "Y"; then
      echo ""
      echo "ERROR: You just said that you wanted to continue the transfer, but you've also"
      echo "       requested that I delete the already existing remote directory.  I don't"
      echo "       think this is what you really want, so I'm exiting now... Goodbye."
      echo ""
      exit
    fi
  else
    mkdir $STAMP_DIR
  fi
}

export STAMP_DIR=$localDir/.transferred_files
validateTransferredFilesDir

if test ! -d "$STAMP_DIR"; then
  # Didn't have permissions to make the directory... so place it in tmp
  echo ""
  echo "  WARNING: Was not able to create $STAMP_DIR directory (bad permissions?)."
  export STAMP_DIR=/tmp/.transferred_files_`basename $localDir`_`whoami`
  echo "           Placing it in $STAMP_DIR instead."
  echo ""
  validateTransferredFilesDir
fi

if test ! -d "$STAMP_DIR"; then
  echo ""
  echo "  ERROR: Did not have permissions to create $STAMP_DIR directory.  Goodbye."
  echo ""
fi

if test "$localDir" == "."; then
  echo ""
  echo "  ERROR: You can't set the local dir to '.'"
  echo ""
  exit 1
fi

echo -n "  Testing: does the local folder ($localDir) exist... "
if test ! -e $localDir; then
  echo ""
  echo ""
  echo "  ERROR: Local directory '$localDir' does not exist"
  echo ""
  exit 1
fi
echo "yes."

echo -n "  Testing: does $REMOTEDIR_PARENT exist on the remote machine... "

#create a script that checks if a file exists and outputs 0 if it does
cat > .testfile.abcdefg << fin
#!/bin/sh
test -d $REMOTEDIR_PARENT;  echo $?
fin

scp -q .testfile.abcdefg $LOGIN:

#execute the script
command="sh .testfile.abcdefg"
test=`$SSH -x $LOGIN $command`

#remove the scripts both locally & remote
$SSH -x $LOGIN "/bin/rm -f .testfile.abcdefg"
/bin/rm -f .testfile.abcdefg

if test "$test" != "0"; then
  echo ""
  echo ""
  echo "  ERROR:  The destination remote directory '$REMOTEDIR_PARENT' does not exist..."
  echo "          Are you sure you typed it in correctly?"
  echo ""
  echo "           NOTE: result of ssh test was: '$test'"
  echo ""
  exit
fi
echo "yes."

echo -n "  Testing: does passwordless access work... "
test=`$SSH -x $LOGIN "echo 'password_access_works'"`
if test "$test" != "password_access_works"; then
  echo ""
  echo ""
  echo "  ERROR: Passwordless access is not working."
  echo "         You must be able to login into the $remote_machine without a password for this script to work"
  echo ""
  exit
fi
echo "yes."

if test `uname` == "Darwin"; then
  HOSTNANE=`hostname`
  MAKE=make
else
  HOSTNANE=`hostname`.`hostname -d`
  MAKE=gmake
fi

echo -n "  Testing: Do we know about the remote operating system?... "
OS=`$SSH -x $LOGIN uname`

if test "$OS" == "Darwin"; then
  # Darwin and Linux are similar enought that this works...
  OS="Linux"
fi

if test "$OS" != "Linux" -a "$OS" != "IRIX64"; then
  echo ""
  echo "  ERROR: There is no pscp2_driver for this operating system: '$OS'"
  echo ""
  exit
fi
echo "yes."

echo "_____________________________________"

#--------------------------------------------------------------------------
# Now do the work

#--------------------------------------------------------------------------
# record some info for posterity

DATA_TRANSFER_RECORD=$localDir/data_transfer_record

touch $DATA_TRANSFER_RECORD

if test ! -f $DATA_TRANSFER_RECORD; then
  # Can't write to that directory... just place it in tmp for now.
  DATA_TRANSFER_RECORD=/tmp/data_transfer_record_`whoami`
fi

echo "--------------------------------" >> $DATA_TRANSFER_RECORD
echo "Data transferred from: $HOSTNAME" >> $DATA_TRANSFER_RECORD
echo "on `date`."                       >> $DATA_TRANSFER_RECORD
echo "Data originally in $localDir"     >> $DATA_TRANSFER_RECORD
echo "Copied by/to $LOGIN:$REMOTEDIR"   >> $DATA_TRANSFER_RECORD
echo ""                                 >> $DATA_TRANSFER_RECORD

# remove the remote directory
if test "$rmDir" == "y" -o "$rmDir" == "Y"; then
  echo "Now removing $REMOTEDIR from $remote_machine if it exists..."
  $SSH -x $LOGIN "/bin/rm -rf $REMOTEDIR; mkdir $REMOTEDIR"
else
  echo $SSH -x $LOGIN \"mkdir -p $REMOTEDIR\"
  $SSH -x $LOGIN "mkdir -p $REMOTEDIR"
  scp $DATA_TRANSFER_RECORD $LOGIN\:$REMOTEDIR
fi

cd $localDir

#-------------------------------
# make a sorted list of potential files to copy
# let the user edit that file with vi
/bin/rm -f $PSCP_FILES

FIND=find
if test `uname` == "AIX"; then
   FIND=/usr/local/gnu/bin/find
fi

$FIND .             -maxdepth 1 -type f -exec basename {} \; | grep -v .transferred_files > $PSCP_FILES
$FIND ./t*          -maxdepth 0 -type d -exec basename {} \; | sort -r                    >>$PSCP_FILES
$FIND ./checkpoints -maxdepth 1                                                                     >>$PSCP_FILES


if test "$transferWholeUda" == "n" -o "$transferWholeUda" == "N"; then
  echo "Now starting an editor:  Remove the files you don't want transferred"

  if test ! $?EDITOR || test "$EDITOR" == ""; then
    echo
    echo WARNING: \$EDITOR is not defined... defaulting to 'vi'
    echo "And 'vi' sometimes doesn't work well..."
    export EDITOR=vi
  fi
fi

$EDITOR $PSCP_FILES
chmod ug+rw $PSCP_FILES
 
echo
echo -n "Starting at: "
date
echo

/usr/bin/time -p $MAKE TAR=tar -f $pscp2dir/pscp2_driver_$OS -j $nproc

echo
echo -n "Ending at: "
date
echo
