# Makefile for GMC User Interface
# 
#------------------------------------------------------------------------------
#
SHELL=/bin/sh
srcdir = .
#JAVAC = javac -g -Xlint:unchecked
JAVAC = javac -g -source 1.4
SOURCE_FILES = \
	BoxGeomPiece.java \
	BoxGeomPiecePanel.java \
	ComputeParticleLocPanel.java\
	CompNeoHookMaterialPanel.java\
	CreateGeomObjectPanel.java\
	CreateGeomPiecePanel.java\
	CylinderGeomPiece.java \
	DecimalField.java \
	DifferenceGeomPiece.java \
	DisplayGeometryPanel.java \
	DisplayPartDistPanel.java \
	DisplayParticleLocPanel.java \
	ElasticPlasticMaterialPanel.java \
	GeneralInputsPanel.java \
	GeometryPanel.java \
	GeomObject.java \
	GeomObjectPanel.java \
	GeomPiece.java \
	GeomPiecePanel.java \
	HelpAboutFrame.java \
	HypoElasticMaterialPanel.java \
	ICEInputsPanel.java \
	ICEMaterialsPanel.java \
	InputGeometryPanel.java \
	InputPartDistPanel.java \
	LightWeightCanvas.java \
	MPMContactInputPanel.java \
	MPMInputsPanel.java \
	MPMMaterialsPanel.java \
	MPMMaterialInputPanel.java \
	Packing.java \
	ParticleGeneratePanel.java \
	Particle.java \
	ParticleList.java \
	ParticleLocGeneratePanel.java \
	ParticleSizeDistInputPanel.java \
	ParticleSize.java \
	Point.java \
	PolygonDouble.java \
	RigidMaterialPanel.java \
	SmoothCylGeomPiece.java \
	TimeInputPanel.java \
	UintahGui.java \
	UintahInputPanel.java \
	UnionGeomPiece.java \
	VariableSaveInputPanel.java \
	Vector3D.java \
	ViscoSCRAMMaterialPanel.java \
	Voronoi.java \
	WholeNumberField.java

#------------------------------------------------------------------------------

all: UintahGui \
	BoxGeomPiece \
	BoxGeomPiecePanel \
	ComputeParticleLocPanel\
	CompNeoHookMaterialPanel \
	CreateGeomObjectPanel\
	CreateGeomPiecePanel\
	CylinderGeomPiece \
	DecimalField\
	DifferenceGeomPiece \
	DisplayGeometryPanel \
	DisplayPartDistPanel\
	DisplayParticleLocPanel\
	ElasticPlasticMaterialPanel \
	GeneralInputsPanel\
	GeometryPanel \
	GeomObject \
	GeomObjectPanel \
	GeomPiece \
	GeomPiecePanel \
	HelpAboutFrame\
	HypoElasticMaterialPanel \
	ICEInputsPanel \
	ICEMaterialsPanel \
	InputGeometryPanel \
	InputPartDistPanel\
	LightWeightCanvas\
	MPMContactInputPanel \
	MPMInputsPanel\
	MPMMaterialsPanel \
	MPMMaterialInputPanel \
	Packing\
	ParticleGeneratePanel\
	Particle\
	ParticleList\
	ParticleLocGeneratePanel\
	ParticleSizeDistInputPanel\
	ParticleSize\
	Point\
	PolygonDouble\
	RigidMaterialPanel \
	SmoothCylGeomPiece \
	TimeInputPanel \
	UintahInputPanel \
	UnionGeomPiece \
	VariableSaveInputPanel \
	Vector3D \
	ViscoSCRAMMaterialPanel \
	Voronoi\
	WholeNumberField

UI: UintahGui

BoxGeomPiece:
	${JAVAC} ${srcdir}/BoxGeomPiece.java

BoxGeomPiecePanel:
	${JAVAC} ${srcdir}/BoxGeomPiecePanel.java

ComputeParticleLocPanel:
	${JAVAC} ${srcdir}/ComputeParticleLocPanel.java

CompNeoHookMaterialPanel:
	${JAVAC} ${srcdir}/CompNeoHookMaterialPanel.java

CreateGeomObjectPanel:
	${JAVAC} ${srcdir}/CreateGeomObjectPanel.java

CreateGeomPiecePanel:
	${JAVAC} ${srcdir}/CreateGeomPiecePanel.java

CylinderGeomPiece:
	${JAVAC} ${srcdir}/CylinderGeomPiece.java

DecimalField:
	${JAVAC} ${srcdir}/DecimalField.java 

DifferenceGeomPiece:
	${JAVAC} ${srcdir}/DifferenceGeomPiece.java

DisplayGeometryPanel:
	${JAVAC} ${srcdir}/DisplayGeometryPanel.java 

DisplayPartDistPanel:
	${JAVAC} ${srcdir}/DisplayPartDistPanel.java 

DisplayParticleLocPanel:
	${JAVAC} ${srcdir}/DisplayParticleLocPanel.java

ElasticPlasticMaterialPanel:
	${JAVAC} ${srcdir}/ElasticPlasticMaterialPanel.java

GeneralInputsPanel:
	${JAVAC} ${srcdir}/GeneralInputsPanel.java 

GeometryPanel:
	${JAVAC} ${srcdir}/GeometryPanel.java 

GeomObject:
	${JAVAC} ${srcdir}/GeomObject.java 

GeomObjectPanel:
	${JAVAC} ${srcdir}/GeomObjectPanel.java 

GeomPiece:
	${JAVAC} ${srcdir}/GeomPiece.java 

GeomPiecePanel:
	${JAVAC} ${srcdir}/GeomPiecePanel.java 

HelpAboutFrame:
	${JAVAC} ${srcdir}/HelpAboutFrame.java 

HypoElasticMaterialPanel:
	${JAVAC} ${srcdir}/HypoElasticMaterialPanel.java

ICEInputsPanel:
	${JAVAC} ${srcdir}/ICEInputsPanel.java 

ICEMaterialsPanel:
	${JAVAC} ${srcdir}/ICEMaterialsPanel.java 

InputGeometryPanel:
	${JAVAC} ${srcdir}/InputGeometryPanel.java 

InputPartDistPanel:
	${JAVAC} ${srcdir}/InputPartDistPanel.java 

LightWeightCanvas:
	${JAVAC} ${srcdir}/LightWeightCanvas.java 

MPMContactInputPanel:
	${JAVAC} ${srcdir}/MPMContactInputPanel.java 

MPMInputsPanel:
	${JAVAC} ${srcdir}/MPMInputsPanel.java 

MPMMaterialsPanel:
	${JAVAC} ${srcdir}/MPMMaterialsPanel.java 

MPMMaterialInputPanel:
	${JAVAC} ${srcdir}/MPMMaterialInputPanel.java 

Packing:
	${JAVAC} ${srcdir}/Packing.java 

ParticleGeneratePanel:
	${JAVAC} ${srcdir}/ParticleGeneratePanel.java 

Particle:
	${JAVAC} ${srcdir}/Particle.java 

ParticleList:
	${JAVAC} ${srcdir}/ParticleList.java 

ParticleLocGeneratePanel:
	${JAVAC} ${srcdir}/ParticleLocGeneratePanel.java 

ParticleSizeDistInputPanel:
	${JAVAC} ${srcdir}/ParticleSizeDistInputPanel.java 

ParticleSize:
	${JAVAC} ${srcdir}/ParticleSize.java 

Point:
	${JAVAC} ${srcdir}/Point.java 

PolygonDouble:
	${JAVAC} ${srcdir}/PolygonDouble.java 

RigidMaterialPanel:
	${JAVAC} ${srcdir}/RigidMaterialPanel.java 

SmoothCylGeomPiece:
	${JAVAC} ${srcdir}/SmoothCylGeomPiece.java

TimeInputPanel:
	${JAVAC} ${srcdir}/TimeInputPanel.java

UintahGui:
	${JAVAC} ${srcdir}/UintahGui.java 

UintahInputPanel:
	${JAVAC} ${srcdir}/UintahInputPanel.java 

UnionGeomPiece:
	${JAVAC} ${srcdir}/UnionGeomPiece.java

VariableSaveInputPanel:
	${JAVAC} ${srcdir}/VariableSaveInputPanel.java

Vector3D:
	${JAVAC} ${srcdir}/Vector3D.java 

ViscoSCRAMMaterialPanel:
	${JAVAC} ${srcdir}/ViscoSCRAMMaterialPanel.java

Voronoi:
	${JAVAC} ${srcdir}/Voronoi.java 

WholeNumberField:
	${JAVAC} ${srcdir}/WholeNumberField.java

clean: 
	rm -f *.class

