/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ptolemy_scirun_StartSCIRun */

#ifndef _Included_ptolemy_scirun_StartSCIRun
#define _Included_ptolemy_scirun_StartSCIRun
#ifdef __cplusplus
extern "C" {
#endif
#undef ptolemy_scirun_StartSCIRun_COMPLETE
#define ptolemy_scirun_StartSCIRun_COMPLETE -1L
#undef ptolemy_scirun_StartSCIRun_CLASSNAME
#define ptolemy_scirun_StartSCIRun_CLASSNAME 1L
#undef ptolemy_scirun_StartSCIRun_FULLNAME
#define ptolemy_scirun_StartSCIRun_FULLNAME 2L
#undef ptolemy_scirun_StartSCIRun_LINKS
#define ptolemy_scirun_StartSCIRun_LINKS 4L
#undef ptolemy_scirun_StartSCIRun_CONTENTS
#define ptolemy_scirun_StartSCIRun_CONTENTS 8L
#undef ptolemy_scirun_StartSCIRun_DEEP
#define ptolemy_scirun_StartSCIRun_DEEP 16L
#undef ptolemy_scirun_StartSCIRun_ATTRIBUTES
#define ptolemy_scirun_StartSCIRun_ATTRIBUTES 32L
/* Inaccessible static: _DEFAULT_WORKSPACE */
/* Inaccessible static: class_00024ptolemy_00024data_00024type_00024Typeable */
/*
 * Class:     ptolemy_scirun_StartSCIRun
 * Method:    getScirun
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ptolemy_scirun_StartSCIRun_getScirun
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     ptolemy_scirun_StartSCIRun
 * Method:    loadNetwork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ptolemy_scirun_StartSCIRun_loadNetwork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
