#!/bin/csh
#
#.......................................................................
# 4/14/98     Todd Harman
# This script is used to automatically transfer files to a 
# remote machine.  
#
#  Usage:   autoftp <password to remote machine>
#.......................................................................

echo""


#.......................................................................
# User defined variables
#.......................................................................
set remote_machine = bingo.mech.utah.edu
set remote_login   = backup
set file_name  = "ICE_body.html"
set file2_name = "ICE.html"
set file3_name = "ICE_menu.html"
set remote_dir     = todd

#..............................
#  Test for passwd
#.............................. 


echo " Input password for $remote_machine"
set remote_psswd = $< 
if ( $remote_psswd == "" ) then
    echo ' You must input passwd '
    echo '  now exiting'
    exit 1
endif

clear
#.......................................................................
# FTP the file to the remote dir
#.......................................................................
  echo ''
  echo ''
  echo ' Now FTP files to $remote_machine'
  echo ''
  ftp -n $remote_machine <<+
      user $remote_login $remote_psswd
      verbose
      prompt
      cd $remote_dir
      put $file_name
      put $file2_name
      put $file3_name
      quit
+


exit (1)
