#! /bin/sh

/bin/rm -f *.aux

#default values
user="yes"
develop="yes"
install="yes"

# command line arguments
while [ "$#" -gt 0 ]; do
    case "$1" in
    -u)
        user="yes"
        develop="no"
        install="no"
        ;;
    -d)
        user="no"
        develop="yes"
        install="no"
        ;;
    -i)
        user="no"
        develop="no"
        install="yes"
        ;;
     -h)
        echo "runLatex: [option]"
        echo "   -u     compile user guide"
        echo "   -d     devlopers guide"
        echo "   -i     installation guide"
        echo "  default is to compile all of the guides"
        exit 1
        ;;
     esac
     shift
done

user_error=0
install_error=0
develop_error=0

if [ $user = "yes" ]; then
  echo "----------------------------------------"
  echo "            User guide"
  echo "----------------------------------------"
  cd UserGuide
  pdflatex  -file-line-error -halt-on-error  user_guide.tex


  if [ $? -eq 0 ]; then
    echo "------------------"
    echo "Now running bibtex"
    echo "------------------"
    bibtex arches
    bibtex ice
    bibtex mpm
    bibtex mpmice
    pdflatex -interaction=batchmode user_guide.tex
    pdflatex -interaction=batchmode user_guide.tex
  else
       user_error=1
  fi
  cd ..
fi


if [ $install = "yes" ]; then
   echo
   echo 
   echo "----------------------------------------"
   echo "            Installation guide"
   echo "----------------------------------------"
   cd InstallationGuide
   pdflatex -file-line-error -halt-on-error installation_guide.tex
   pdflatex installation_guide.tex
   if [ $? -ne 0 ]; then 
      install_error=1
   else
      install_error=0
   fi
   cd ..
fi

if [ $develop = "yes" ]; then
  echo
  echo 
  echo "----------------------------------------"
  echo "            Developer guide"
  echo "----------------------------------------"
  cd DeveloperGuide 
  pdflatex -file-line-error -halt-on-error UintahAPI.tex
  pdflatex UintahAPI.tex
  if [ $? -ne 0 ]; then
     develop_error=1
  else
     develop_error=0
  fi
  cd ..
fi

#cleanup
echo "------------------"
echo "now cleaning up"
find . -name "*.out" -exec /bin/rm -f {} \;
find . -name "*.aux" -exec /bin/rm -f {} \;
find . -name "*.log" -exec /bin/rm -r {} \;
find . -name "*.bbl" -exec /bin/rm -r {} \;
find . -name "*.blg" -exec /bin/rm -r {} \;

echo "User error = " ${user_error}
echo "Install error = " ${install_error}
echo "Develop error = " ${develop_error}


exit $(( (( $user_error || $install_error )) ||  $develop_error ))

