#! /bin/bash

THELIB=RadProps

source ../HelperBuildScripts/setupEnv.sh

rm -rf CMakeCache.txt CMakeFiles *.cmake
rm -rf ${INSTALL_HERE}/*

if test "$BUILD_CUDA" = "yes"; then
  FLAGS="-DENABLE_THREADS=OFF
         -DENABLE_CUDA=ON
         -DDISABLE_INTROSPECTION=ON
         -DCUDA_ARCHITECTURE_MINIMUM=\"3.5\" 
         -DCUDA_HOST_COMPILER=/opt/gcc/4.9.3/bin/g++"
fi

cmake_cmd=\
"
  cmake
    $FLAGS
    -DRadProps_ENABLE_TESTING=OFF
    -DRadProps_ENABLE_PREPROCESSOR=OFF
    -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE}
    -DCMAKE_C_COMPILER=$CC
    -DCMAKE_CXX_COMPILER=$CXX
    -DCMAKE_CXX_FLAGS=\"-fPIC\"
    -DTabProps_DIR=$INSTALL_BASE/$COMP/TabProps/share
    ../RadProps
"

echo ""
echo "Running CMAKE command:"
echo $cmake_cmd
echo ""

eval $cmake_cmd

if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "RadProps: Updating installation permissions for ${INSTALL_HERE}..."
  chmod -R go+rX ${INSTALL_HERE}/../..
fi

