#
# This is not the real makefile - there is a single top level
# makefile, at $(TOP).  The targets for this directory are
# specified in sub.mk in this directory
#
SRCTOP := .
OBJTOP := ../../../..
HERE_TARGET := lib/libUintah_Components_MPM_Burn.so

include $(OBJTOP)/$(SRCTOP)/scripts/default.mk
