
#ifndef TK_RANGE_H
#define TK_RANGE_H 1

/*
 * Defaults for ranges:
 */

#define DEF_RANGE_RANGE_COLOR		BLACK
#define DEF_RANGE_ACTIVE_BG_COLOR	ACTIVE_BG
#define DEF_RANGE_ACTIVE_BG_MONO	BLACK
#define DEF_RANGE_BG_COLOR		NORMAL_BG
#define DEF_RANGE_BG_MONO		WHITE
#define DEF_RANGE_BIG_INCREMENT		"0"
#define DEF_RANGE_BORDER_WIDTH		"2"
#define DEF_RANGE_COMMAND		""
#define DEF_RANGE_CURSOR		""
#define DEF_RANGE_DIGITS		"0"
#define DEF_RANGE_FONT			"-Adobe-Helvetica-Bold-R-Normal--*-120-*-*-*-*-*-*"
#define DEF_RANGE_FG_COLOR		BLACK
#define DEF_RANGE_FG_MONO		BLACK
#define DEF_RANGE_FROM			"0"
#define DEF_RANGE_HIGHLIGHT		"black"
#define DEF_RANGE_HIGHLIGHT_WIDTH	"2"
#define DEF_RANGE_LABEL			""
#define DEF_RANGE_LENGTH		"100"
#define DEF_RANGE_ORIENT		"vertical"
#define DEF_RANGE_RELIEF		"flat"
#define DEF_RANGE_REPEAT_DELAY	"300"
#define DEF_RANGE_REPEAT_INTERVAL	"100"
#define DEF_RANGE_RESOLUTION		"1"
#define DEF_RANGE_TROUGH_COLOR		TROUGH
#define DEF_RANGE_TROUGH_MONO		WHITE
#define DEF_RANGE_SHOW_VALUE		"1"
#define DEF_RANGE_NON_ZERO		"0"
#define DEF_RANGE_SLIDER_LENGTH		"15"
#define DEF_RANGE_STATE			"normal"
#define DEF_RANGE_TICK_INTERVAL		"0"
#define DEF_RANGE_TO			"100"
#define DEF_RANGE_VARIABLE		""
#define DEF_RANGE_WIDTH			"15"

#endif
