#!/bin/csh

#______________________________________________________________________
# findTabs 
#
#  This script searches all *.h and *.cc files 
#  and displays all the lines that have tabs in them
#  If the user adds a "y" to the command line then the tabs 
#  will be converted to spaces.
#______________________________________________________________________

set convert = "n"
if ( $#argv > 0) then
  set convert = $argv
endif

set these = `find . -type f -name "*.cc" -or -name "*.h"`

#__________________________________
# display the tabs in the files
foreach X ($these[*])
  echo "File $X"
  cat -v -t -e $X |grep  '\^I'
end


#__________________________________
# convert the tabs to spaces
echo "--------------------------------------------$convert"
if ($convert == "y" ) then
  foreach X ($these[*])
    echo "File $X"
    
    set nTabs = `cat -v -t -e $X |grep -c '\^I'` 
    
    if ( $nTabs > 0 ) then
      echo "Now converting tabs to spaces in file $X"
      expand $X >& $X.tmp
      mv $X.tmp  $X
    endif
  end
  
endif

exit
