# Generated automatically from Makefile.in by configure.
SRCTOP   = ../../..
SRCDIR   = .
OBJTOP   = ../../..

SRCS     = SlaveController.cc

INCLUDES = -I$(OBJTOP)/src \
           -I$(SRCDIR)/.. -I$(SRCDIR)/../../SCICore -I$(SRCDIR)/../../3rdParty

include $(SRCTOP)/scripts/objs.mk
