#!/bin/bash

TEST_NAME=$1
TEST_TIMEFILE=$2
COMPARISON_TIMEFILE=$3

echo "group $COMMON_GROUP"

if [ ! -f $TEST_TIMEFILE ]; then
    echo "No performance output found.  Can't do performance test."
    exit 5
fi

if [ ! -f $COMPARISON_TIMEFILE ]; then
    echo "No previous performance output.  Storing results."
    cp $TEST_TIMEFILE $COMPARISON_TIMEFILE
    chgrp $COMMON_GROUP $COMPARISON_TIMEFILE
    chmod g+rw $COMPARISON_TIMEFILE
    exit -1
fi

error=0

echo "Performing performance check"
percent=`performance_percent.pl $TEST_TIMEFILE $COMPARISON_TIMEFILE`

if [ $percent -gt "10" ]; then
    echo "***Performance test failed"
    echo " -- Time increased by %$percent" > performance_shortmessage.txt
    error=2
elif [ $percent -gt "0" ]; then
    echo " -- Time increased by %$percent" > performance_shortmessage.txt
elif [ $percent -lt "0" ]; then
    let percent_improvement=-$percent;
    
    if [ $percent -lt "-5" ]; then
	echo "Preformance passed with some improvement!!"
	echo " -- Performance improved by %$percent_improvement, replacing timestamp" > performance_shortmessage.txt
	cp $TEST_TIMEFILE $COMPARISON_TIMEFILE
	chgrp $COMMON_GROUP $COMPARISON_TIMEFILE
	chmod g+rw $COMPARISON_TIMEFILE
    else
	echo " -- Performance improved by %$percent_improvement" > performance_shortmessage.txt
    fi
else
    echo "" > performance_shortmessage.txt
    echo "Performance check passed!"
fi

exit $error
