#!/bin/csh
#.......................................................................
#  This script searches parses the output file from sus and 
#  generates a data file that's used for scaling plots
# 
#  output file name must begin with "out"
#  
#.......................................................................

set timestep = "11"  # timestep to extract elapsed time from.

/bin/rm  data
touch data

foreach X ( out*)

  echo $X > .file
  grep "Patch layout:" $X | cut -d"(" -f2 > .patches
  grep processors $X | awk -F" " '{ print $2 }' > .processors
  grep "(timestep $timestep)" $X | awk -F "=" '{print $4}' | cut -d "," -f1 > .elapsedTime
  
  paste -d " " .file .patches .processors .elapsedTime >> data
  
  echo "working on $X"
  
end

more data

exit
