% Adapted from FDS' plotspec.m
% http://code.google.com/p/fds-smv/source/browse/trunk/FDS/trunk/Utilities/
% Matlab/scripts/plotspec.m
% 
% function: energy_spectrum_plot_all
% author: Tony Saad
% date: Sept 2012
%
% energy_spectrum_plot_all: plots all data for the energy spectrum
% 
% calculation
% usage: energy_spectrum_plot_all('ke_wasatch_wale_32','wasatch','wale',32,'Wale model, C_w = 0.7')
%
% 1. Run your turbulent flow simulation
% 2. Use lineextract to save your u, v, and w velocities at t = 0.28s and t
% = 0.66s as these correspond to the experimental datapoints
% 3. With lineextract, save your output as
% uvel/vvel/wvel_basename_t0.28s/t0.66s.txt
% for example: vvel_32_wasatch_csmag_t0.28s.txt is the lineextract for the
% y-velocity field. here, the basename is 32_wasatch_csmag.
% 4. Execute energy_spectrum_plot_all. Here, the output_filename designates
% the pdf filename of the exported figure, base_name denotes the
% base_name in the lineextract output filename, and figure_title
% is a string that corresponds to the figure's title. For example,
% energy_spectrum_plot_all('ke_wasatch_wale_32','32_wasatch_wale','Wale model, C_w = 0.7')
% will look for lineextract files with names:
% uvel_32_wasatch_wale_t0.28s.txt
% vvel_32_wasatch_wale_t0.28s.txt
% wvel_32_wasatch_wale_t0.28s.txt
% uvel_32_wasatch_wale_t0.66s.txt
% vvel_32_wasatch_wale_t0.66s.txt
% wvel_32_wasatch_wale_t0.66s.txt
% The output pdf figure will have the title ke_wasatch_wale_32.pdf and will
% have the title: Wale model, C_w = 0.7
%

function [] = energy_spectrum_plot_all(output_filename,base_name, figure_title)

  close all   % cleanup  
  plot_style  % set some plot style parameters

  % set figure properties
  set(gca,'Units',Plot_Units)
  set(gca,'Position',[Plot_X,Plot_Y,Plot_Width,Plot_Height])
  set(gcf,'DefaultLineLineWidth',Line_Width)

  % plot the cbc experimental data
  plot_energy_spectrum_cbc();

  % format axes
  set(gca,'FontName',Font_Name)
  set(gca,'FontSize',Key_Font_Size)
  axis([10 1000 1/1e6 1000/1e6])
  ylabel('E(k), m^3/s^2','FontSize',Title_Font_Size)
  xlabel('k, 1/m','FontSize',Title_Font_Size)
  title(figure_title);

  % plot initial condition spectrum - this is taken from the original cbc_uvw
  % data generated by Randy McDermott
  plot_energy_spectrum_uvw('cbc32_uvw.csv',9*2*pi/100,'k.-');

  % plot the spectrum at t = 0.28s
  uvelFileName = strcat('uvel_',base_name,'_t0.28s.txt');
  vvelFileName = strcat('vvel_',base_name,'_t0.28s.txt');
  wvelFileName = strcat('wvel_',base_name,'_t0.28s.txt');
  plot_energy_spectrum_uda(uvelFileName,vvelFileName,wvelFileName,9*2*pi/100, 'r.-');

  % plot the spectrum at t = 0.66s
  uvelFileName = strcat('uvel_',base_name,'_t0.66s.txt');
  vvelFileName = strcat('vvel_',base_name,'_t0.66s.txt');
  wvelFileName = strcat('wvel_',base_name,'_t0.66s.txt');
  k_nyquist = plot_energy_spectrum_uda(uvelFileName,vvelFileName,wvelFileName,9*2*pi/100, 'b.-');

  % plot the nyquist limit
  plot_nyquist_limit(k_nyquist);

  % print to pdf
  set(gcf,'Visible',Figure_Visibility);
  set(gcf,'PaperUnits',Paper_Units);
  set(gcf,'PaperSize',[Paper_Width (Paper_Height)]);
  set(gcf,'PaperPosition',[0.0 0.0 Paper_Width (Paper_Height)]);
  print(gcf,'-dpdf',['',output_filename]);

end
