#!/bin/csh -f -x
setenv name `whoami`
setenv EDITOR vi
cvs commit
set release = `cat etc/release`
cvs rdiff -c -r $name"_"$release work > patch.$release
gzip patch.$release
@ release ++
cvs update -d
cvs tag $name"_"$release
echo $release > etc/release
