#!/bin/csh -f -x
setenv name `whoami`
setenv EDITOR vi
cvs commit
set release = `cat etc/release`
cvs rdiff -u -r $name_$release work > patch.$release
gzip patch.$release
@ release ++
cvs tag $name_$release
echo $release > etc/release
