# Generated automatically from Makefile.in by configure.
SRCTOP   = ../..
SRCDIR   = .
OBJTOP   = ../..

ifeq (no,yes)
PARALLEL_SRCS = 

endif

SRCS     =  MultiBrick.cc VolumeOctree.cc Brick.cc TexBrick.cc \
	VolumeUtils.cc $(PARALLEL_SRCS)

INCLUDES = -I$(SRCTOP) -I$(OBJTOP)

include $(SRCTOP)/scripts/objs.mk
