#!/bin/sh

#______________________________________________________________________
#  startLocalTest:
#     This script executes the regression tests for a single component


#__________________________________
# define environmental variables and export them
HTMLLOG=""
LOCAL_OR_NIGHTLY_TEST="local"
mallocstrict="no"
OS=`uname -s`
PARALLELISM=8
WEBLOG=""

BUILD_DIR=/dev/null

export mallocstrict  BUILD_DIR  HTMLLOG WEBLOG LOCAL_OR_NIGHTLY_TEST OS

#__________________________________
unset SHELL
umask 002

show_help=0
if [ "$#" == 0 ]; then
    show_help=1
fi

# command line arguments
while [ "$#" -gt 0 ]; do
    case "$1" in
    -build_dir)
        if [ "$#" -gt 1 ]; then
            shift
            BUILD_DIR="$1"
        fi
        ;;
    -component)
        if [ "$#" -gt 1 ]; then
            shift
            componentTest="$1"
        fi
        ;;
    -help)
        show_help=1
        ;;
     *)
        echo "$1: Unknown option, -help for help"
        exit 1
        ;;
     esac
     shift
done

# usage string - exit
if [ $show_help != "0" ]; then
    cat <<EOF
    Usage: localTests_masterScript 
        Options:
            -build_dir:             The top level directory the code was compiled in.  For example, 100110SCIRun/opt_Linux.
            -component:             Component regression test to run.
            -help:                  Display this option summary
EOF
    exit 0
fi




cd "${BUILD_DIR}"

TEST_DATA="${BUILD_DIR}/TestData"
#__________________________________
#    - generate the symbolic links
#    - check for the goldStandards
mkdir local_RT
cd    local_RT

if [ ! -d TestScripts ]; then
  ln -s ../../src/R_Tester TestScripts
fi

if [ ! -f replace_all_GS ]; then
  ln -s ../../src/R_Tester/helpers/replace_all_GS replace_all_GS
fi

if [ ! -d susdir ]; then
  ln -s ../StandAlone susdir
fi

if [ ! -d inputs ]; then
  ln -s ../../src/StandAlone/inputs inputs
fi

if [ -d goldStandard ]; then
  rm -f goldStandard
fi
ln -s "${TEST_DATA}" goldStandard


# checking for GoldStandards
if [ ! -d "$TEST_DATA" ]; then
  echo "TEST_DATA directory doesn't exist: $TEST_DATA"
  exit -1;
fi

#__________________________________
# Now run the test
echo "TIME STAMP: Regression Tester Starting at:"
date
echo "Running Tests"


# create the do<component>tests  python script
doTestScript="do${componentTest}tests"
echo "#!/bin/tcsh"            >  "$doTestScript"
echo "setenv PATH $PATH"      >> "$doTestScript"
echo "setenv OS $OS"          >> "$doTestScript"
echo "setenv SCI_DEBUG \"\""  >> "$doTestScript"

echo "python TestScripts/$componentTest susdir inputs goldStandard local $PARALLELISM "'$1' >> "$doTestScript"

/bin/chmod a+x "$doTestScript"

#__________________________________
# run the python script that contains all the
# tests for that component

"$doTestScript" > "${componentTest}.log"  2>&1
retval=$?

cat ${componentTest}.log

echo "TIME STAMP: REGRESSION TESTER DONE AT:"
date

exit $retval

