# ----------------------------------------------------------------- #
#                                                                   #
# This file: Makefile                                               #
#                                                                   #
# ----------------------------------------------------------------- #

PAPER      = overview

all : 
	pdflatex $(PAPER).tex

clean : 
	rm -f *.log *.blg $(PAPER).dvi $(PAPER).ps *.bbl *~ *.bak *.backup *.log *.aux
