THISDIR = Thread

SECTION = SCICore

include $(TOP)/make.defaults

C_DIR = $(TOP)/src/SCICore/$(THISDIR)
O_DIR = $(ARCHDIR)/$(THISDIR)

INCLUDES = -I$(C_DIR)

LIB      = $(ARCHDIR)/lib/lib$(THISDIR).so

SHAREDLIB = $(CC) $(SHAREDFLAGS)

OBJS =  $(O_DIR)/AsyncReply.o $(O_DIR)/Parallel.o $(O_DIR)/Thread.o

#OBJS =  AsyncReply.o Parallel.o Thread.o AtomicCounter.o \
#	ParallelBase.o ThreadAlert.o Barrier.o PoolMutex.o \
#	ThreadError.o ConditionVariable.o Profiler.o \
#	ThreadEvent.o CrowdMonitor.o RealtimeThread.o ThreadGroup.o \
#	LockUnlock.o RecursiveMutex.o ThreadListener.o Mailbox.o \
#	Reducer.o ThreadTopology.o Runnable.o WorkQueue.o Mutex.o \
#	Semaphore.o Thread_irix.o


LIBS = -L$(ARCHDIR)/lib -lMalloc -lExceptions 

all : $(LIB)

clean :
	rm $(O_DIR)/*.o $(LIB) 
	rm -R $(TEMPLATEDIR)

soclean :
	rm $(LIB)

$(LIB): $(OBJS)
	$(SHAREDLIB) -o $(LIB) $(OBJS) $(LIBS)

CCM = $(CC) -MDupdate $(O_DIR)/Makedepend

AsyncReply.o:	AsyncReply.cc
	$(CCM) $(CFLAGS) -c $< -o $@ $(INCLUDES)

$(O_DIR)/Parallel.o:	Parallel.cc
	$(CCM) $(CFLAGS) -c $< -o $@ $(INCLUDES)

$(O_DIR)/Thread.o:	Thread.cc
	$(CCM) $(CFLAGS) -c $< -o $@ $(INCLUDES)

$(O_DIR)/Makedepend:
	touch $(O_DIR)/Makedepend

include $(O_DIR)/Makedepend
