/*
 * This file was automatically generated by SCC - do NOT edit!
 * You should edit Profiler.scc instead 
 */

#ifndef SCI_THREAD_PROFILER_H
#define SCI_THREAD_PROFILER_H 1



#include "Runnable.h"

#include <stdio.h>

/**************************************
 
CLASS
   Profiler
   
KEYWORDS
   Profiler
   
DESCRIPTION
   <i>No documentation provided</i>
  
PATTERNS


WARNING
   
****************************************/

class Profiler  : public Runnable {
    
    FILE* in;
    FILE* out;
    //////////
    // <i>No documentation provided</i>
    virtual void run() ;
public:
    //////////
    // <i>No documentation provided</i>
    Profiler() ;

    //////////
    // <i>No documentation provided</i>
    Profiler(FILE* in, FILE* out) ;

    //////////
    //  <i>No documentation provided</i>
    ~Profiler() ;
};

#endif


