# Makefile.vc
#
# written by Chris Moulding 7/99

###########################  EDIT HERE  ###########################

DLLNAME = PSECommon
EXENAME = 

OBJS = share\PSECommonDLLEntry.odll\
#      Modules\
	


CF   = -DBUILD_PSECOMMON
LF   = 

INCS = 
         
LIBS = 

###################################################################

!include <$(TOP)\src\Makefile.vc.master>