#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTests import runSusTests

UNUSED = [ 	    ("periodic_disks", "periodic_disks.ups", "", 6, "Linux")	]

TESTS = [   ("disks2mat4patch4proc", "disks2mat4patch.ups", "", 4, "ALL"), \
	    ("heatcond2mat", "heatcond2mat.ups", "", 1, "ALL"), \
	    ("foam_crush", "foam_crush.ups", "", 4, "Linux"), \
    	]

exit(runSusTests(argv, TESTS, "mpm"))
