#!/bin/csh
#__________________________________
#  This script pulls out data from sus 
#   output and plots it using gnuplot.
#  Usage:
#     plot_shockTube <dat> <dump postScript File (y/Y), default is no>
#__________________________________

if( $#argv == 0 ) then
  echo "plot_shockTube_1L <dat file> <dat file> <dump postScript File (y/Y), default is no>"
  exit(1)
endif
set dat = $argv[1]
if ( !(-e $dat) ) then
    echo "Couldn't find your dat $dat"
  exit(1)
endif

set hardcopy = "n"
if ( $#argv == 2 ) then
  set hardcopy = $argv[3]
endif


echo "set terminal x11 1" >gp
#__________________________________
# if making a hardcopy
if( $hardcopy == "y" || $hardcopy == "Y" ) then 
echo "Generating the postscript file shockTube.ps"
rm -f gp

cat > gp << fin
set terminal postscript color solid "Times-Roman" 9 portrait
set output "shockTube.ps"
fin
endif

#__________________________________
# generate the  plot script
cat >> gp << fin
set ytics
set xtics
set mxtics
set mytics
set grid xtics ytics
set title ""

#__________________________________
#   Pressure
#__________________________________
set autoscale
set multiplot
set size 1,0.25  
set origin 0.0,0.0

set ylabel "Pressure"
set y2tics
#set xrange [0:1]
set pointsize 0.3
plot  '$dat'             using 1:4 with linespoints t ''

#__________________________________
#   Temperature
#__________________________________
set origin 0.0,0.25

set ylabel "Temperature"
plot  '$dat'              using 1:5 with linespoints t 'Sim 1'

#__________________________________
#  velocity x-component
#__________________________________
set origin 0.0,0.5

set ylabel "Velocity"
plot  '$dat'               using 1:3 with linespoints t 'Sim 1'
#__________________________________
#   density
#__________________________________
set origin 0.0,0.75

set ylabel "Density"
plot  '$dat'              using 1:2 with linespoints t 'Sim 1'
      
set nomultiplot 
pause -1 "Hit return to continue"
fin
#__________________________________
# plot it up
gnuplot gp


#__________________________________
# clean up
rm -f gp 
