#!/bin/csh
#
#_____________________________________________________________________.
#  This script spits all of ICE's debugSwitches and printData variables
#_____________________________________________________________________.

# parce out the build directory 
set numHits = 0
@ counter = 0
while ($numHits != 1 && $counter < 15)
  @ counter ++
  set buildDir = `pwd | cut -d/ -f1-$counter`
  set numHits = `echo $buildDir|grep -c SCIRun`
end  

set iceDir = $buildDir/src/Packages/Uintah/CCA/Components/ICE
echo "_______________________________________printData variables"
grep dbg $iceDir/ICEDebug.cc | grep get | cut -d \" -f2

echo "_______________________________________switches"
set switches = `grep switch $iceDir/ICEDebug.cc | grep == | cut -d \" -f4`
foreach X ($switches[*]:q)
  echo "<debug label =" '"'$X'"'"/>"
end

echo " Example Usage:"
echo
echo "  <Debug>"
echo "      <dbg_timeStart>       1.00        </dbg_timeStart>"
echo "      <dbg_timeStop>        0.01        </dbg_timeStop>"
echo "      <dbg_outputInterval>  1e-9        </dbg_outputInterval>"
echo "      <dbg_BeginIndex>     [[7,3,3]]    </dbg_BeginIndex>"
echo "      <dbg_EndIndex>       [[12,7,7]]   </dbg_EndIndex>"
echo "      <dbg_Matls>           [0]         </dbg_Matls>"
echo "      <dbg_Level>           [1]         </dbg_Level>"
echo "      <dbg_SigFigs>         [16]        </dbg_SigFigs>"

echo "      <debug label = ""switchDebug_equil_press""/>"
echo "      <debug label = ""switchDebug_vel_FC""/>"
echo "      <debug label = ""switchDebug_Exchange_FC""/>"
echo "      <debug label = ""switchDebug_press""/>"       
echo "      <debug label = ""switchDebug_explicit_press""/>"   
echo "      <debug label = ""switchDebug_PressFC""/>" 
echo "      <debug label = ""switchDebug_LagrangianValues""/>"  
echo "      <debug label = ""switchDebug_Source_Sink""/>"     
echo "      <debug label = ""switchDebug_advance_advect""/>" 
echo "    </Debug>"
echo ""
echo "Example of how to exract certain variables from the excess output"
echo 'grep -A3 -b2 "cmass\|gmass\|rho_CC\|rho_micro\|sp_vol\|timestep\|vol_frac\|mass_L" spew.txt'

exit
