#! /bin/csh

/bin/rm -f *.aux

mkdir -p PDF

#set OUTPUT_DIR="-output-directory=PDF"

#pdflatex  --halt-on-error $OUTPUT_DIR uintah.tex
pdflatex  --halt-on-error  uintah.tex

if( $status == "0" ) then
  echo "------------------"
  echo "Now running bibtex"
  echo "------------------"
  #bibtex arches
  bibtex ice
  bibtex mpm
  bibtex mpmice
#  pdflatex -interaction=batchmode $OUTPUT_DIR uintah.tex
#  pdflatex -interaction=batchmode $OUTPUT_DIR uintah.tex
  pdflatex -interaction=batchmode uintah.tex
  pdflatex -interaction=batchmode uintah.tex
endif

