#! /bin/sh

/bin/rm -f *.aux


echo "----------------------------------------"
echo "            User guide"
echo "----------------------------------------"
cd UserGuide
pdflatex  -file-line-error --halt-on-error  uintah.tex


if [ $? -eq 0 ]; then
  echo "------------------"
  echo "Now running bibtex"
  echo "------------------"
  #bibtex arches
  bibtex ice
  bibtex mpm
  bibtex mpmice
  pdflatex -interaction=batchmode uintah.tex
  pdflatex -interaction=batchmode uintah.tex
fi

echo
echo 
echo "----------------------------------------"
echo "            Installation guide"
echo "----------------------------------------"
cd ../InstallationGuide
pdflatex -file-line-error --halt-on-error installation.tex

echo
echo 
echo "----------------------------------------"
echo "            Developer guide"
echo "----------------------------------------"
cd ../DeveloperGuide 
pdflatex -file-line-error --halt-on-error UintahAPI.tex


#cleanup
echo "------------------"
echo "now cleaning up"
find . -name "*.out" -exec /bin/rm -f {} \;
find . -name "*.aux" -exec /bin/rm -f {} \;
find . -name "*.log" -exec /bin/rm -r {} \;

