#!/bin/csh
#__________________________________
# 10/04/11
#  updateUps  <ups files>
#    This script changes the names of xml tags inside a ups file
#__________________________________
if ($#argv == 0 ) then
  echo " Usage:  updateUps <list of ups files>"
  exit(0)
endif

set these = ($argv[*])
 
foreach fff ( $these[*]:q )

  cp $fff $fff.org
  echo "Now modifying " $fff
  #__________________________________
  # change parameters -> Parameters
  # change res_tol    -> tolerance
  # change max_iter   -> maxiterations
  # from all lines between <PressureSolver> and </PressureSolver>
  sed  -i /"<PressureSolver"/,/"\/PressureSolver"/s/"parameters"/"Parameters"/g  $fff
  sed  -i /"<PressureSolver"/,/"\/PressureSolver"/s/"res_tol"/"tolerance"/g      $fff 
  sed  -i /"<PressureSolver"/,/"\/PressureSolver"/s/"max_iter"/"maxiterations"/g $fff
  
end
exit()
