#! /bin/sh

#
# Name:   bigmac_hack
# Author: Davison de St. Germain
#
# This script is to be run on Macs that use Mac Ports.  It should be used in this sequence:
#
# - Run configure
# - Run this script
# - Run make
#
# The reason this is necessary is that there is a system libz and a
# (different) Mac Ports version of libz.  We could try to update
# configure to allow the user to specify the directory that libz is
# in, and to set LIBRARY variables correctly, but for a number of
# reasons it would be hard to make it robust across all platforms.
# Thus, at least for now, it is deemed simpler to just run this
# script.
#
# The purpose of this script is to just add '-L/opt/local/lib' to the
# Z_LIBRARY variable in configVars.mk.
#
# While this is designed primarily to be used by the BuildBot on
# BigMac, it can be used by anyone on a Mac that uses Mac Ports and
# shows linking issues with libz.
#

sed "s,Z_LIBRARY :=  -lz,Z_LIBRARY := -L/opt/local/lib -lz," configVars.mk > configVars.mk.new

mv configVars.mk.new configVars.mk
