# Makefile for GMC User Interface
# 
#------------------------------------------------------------------------------
#
SHELL=/bin/sh
srcdir = .
#JAVAC = javac -g -Xlint:unchecked
JAVAC = javac -g -source 1.4
SOURCE_FILES = \
	BoxGeomPiece.java \
	BoxGeomPiecePanel.java \
	ComputeParticleLocPanel.java\
	CompNeoHookMaterialPanel.java\
	CreateGeomObjectPanel.java\
	CreateGeomPiecePanel.java\
	CylinderGeomPiece.java \
	DecimalField.java \
	DecimalVectorField.java \
	DifferenceGeomPiece.java \
	DisplayGeometryFrame.java \
	DisplayPartDistFrame.java \
	DisplayParticleLocFrame.java \
	ElasticPlasticMaterialPanel.java \
	GeneralInputsPanel.java \
	GeometryPanel.java \
	GeomObject.java \
	GeomObjectPanel.java \
	GeomPiece.java \
	GeomPiecePanel.java \
	GridBCPanel.java \
	HelpAboutFrame.java \
	HypoElasticMaterialPanel.java \
	ICEInputsPanel.java \
	ICEMaterialsPanel.java \
	ICEMaterialInputPanel.java \
	InputGeometryPanel.java \
	InputPartDistPanel.java \
	IntegerField.java \
	IntegerVectorField.java \
	LightWeightCanvas.java \
	MPMContactInputPanel.java \
	MPMInputsPanel.java \
	MPMMaterialsPanel.java \
	MPMMaterialInputPanel.java \
	MPMICEExchangePanel.java \
	Packing.java \
	ParticleGeneratePanel.java \
	Particle.java \
	ParticleList.java \
	ParticleLocGeneratePanel.java \
	ParticleSizeDistInputPanel.java \
	ParticleSize.java \
	Point.java \
	PolygonDouble.java \
	RigidMaterialPanel.java \
	SmoothCylGeomPiece.java \
	TimeInputPanel.java \
	UintahGui.java \
	UintahInputPanel.java \
	UnionGeomPiece.java \
	VariableSaveInputPanel.java \
	Vector3D.java \
	ViscoSCRAMMaterialPanel.java \
	Voronoi.java 

#------------------------------------------------------------------------------

all: UintahGui \
	BoxGeomPiece \
	BoxGeomPiecePanel \
	ComputeParticleLocPanel\
	CompNeoHookMaterialPanel \
	CreateGeomObjectPanel\
	CreateGeomPiecePanel\
	CylinderGeomPiece \
	DecimalField\
	DecimalVectorField\
	DifferenceGeomPiece \
	DisplayGeometryFrame \
	DisplayPartDistFrame\
	DisplayParticleLocFrame\
	ElasticPlasticMaterialPanel \
	GeneralInputsPanel\
	GeometryPanel \
	GeomObject \
	GeomObjectPanel \
	GeomPiece \
	GeomPiecePanel \
	GridBCPanel \
	HelpAboutFrame\
	HypoElasticMaterialPanel \
	ICEInputsPanel \
	ICEMaterialsPanel \
	ICEMaterialInputPanel \
	InputGeometryPanel \
	InputPartDistPanel\
	IntegerField \
	IntegerVectorField \
	LightWeightCanvas\
	MPMContactInputPanel \
	MPMInputsPanel\
	MPMMaterialsPanel \
	MPMMaterialInputPanel \
	MPMICEExchangePanel \
	Packing\
	ParticleGeneratePanel\
	Particle\
	ParticleList\
	ParticleLocGeneratePanel\
	ParticleSizeDistInputPanel\
	ParticleSize\
	Point\
	PolygonDouble\
	RigidMaterialPanel \
	SmoothCylGeomPiece \
	TimeInputPanel \
	UintahInputPanel \
	UnionGeomPiece \
	VariableSaveInputPanel \
	Vector3D \
	ViscoSCRAMMaterialPanel \
	Voronoi

UI: UintahGui

BoxGeomPiece: BoxGeomPiece.java
	${JAVAC} ${srcdir}/BoxGeomPiece.java

BoxGeomPiecePanel: BoxGeomPiecePanel.java
	${JAVAC} ${srcdir}/BoxGeomPiecePanel.java

ComputeParticleLocPanel: ComputeParticleLocPanel.java 
	${JAVAC} ${srcdir}/ComputeParticleLocPanel.java

CompNeoHookMaterialPanel: CompNeoHookMaterialPanel.java
	${JAVAC} ${srcdir}/CompNeoHookMaterialPanel.java

CreateGeomObjectPanel: CreateGeomObjectPanel.java
	${JAVAC} ${srcdir}/CreateGeomObjectPanel.java

CreateGeomPiecePanel: CreateGeomPiecePanel.java
	${JAVAC} ${srcdir}/CreateGeomPiecePanel.java

CylinderGeomPiece: CylinderGeomPiece.java
	${JAVAC} ${srcdir}/CylinderGeomPiece.java

DecimalField: DecimalField.java
	${JAVAC} ${srcdir}/DecimalField.java 

DecimalVectorField: DecimalVectorField.java
	${JAVAC} ${srcdir}/DecimalVectorField.java 

DifferenceGeomPiece: DifferenceGeomPiece.java
	${JAVAC} ${srcdir}/DifferenceGeomPiece.java

DisplayGeometryFrame: DisplayGeometryFrame.java
	${JAVAC} ${srcdir}/DisplayGeometryFrame.java 

DisplayPartDistFrame: DisplayPartDistFrame.java
	${JAVAC} ${srcdir}/DisplayPartDistFrame.java 

DisplayParticleLocFrame: DisplayParticleLocFrame.java
	${JAVAC} ${srcdir}/DisplayParticleLocFrame.java

ElasticPlasticMaterialPanel: ElasticPlasticMaterialPanel.java
	${JAVAC} ${srcdir}/ElasticPlasticMaterialPanel.java

GeneralInputsPanel: GeneralInputsPanel.java
	${JAVAC} ${srcdir}/GeneralInputsPanel.java 

GeometryPanel: GeometryPanel.java
	${JAVAC} ${srcdir}/GeometryPanel.java 

GeomObject: GeomObject.java
	${JAVAC} ${srcdir}/GeomObject.java 

GeomObjectPanel: GeomObjectPanel.java
	${JAVAC} ${srcdir}/GeomObjectPanel.java 

GeomPiece: GeomPiece.java
	${JAVAC} ${srcdir}/GeomPiece.java 

GeomPiecePanel: GeomPiecePanel.java
	${JAVAC} ${srcdir}/GeomPiecePanel.java 

GridBCPanel: GridBCPanel.java
	${JAVAC} ${srcdir}/GridBCPanel.java 

HelpAboutFrame: HelpAboutFrame.java
	${JAVAC} ${srcdir}/HelpAboutFrame.java 

HypoElasticMaterialPanel: HypoElasticMaterialPanel.java
	${JAVAC} ${srcdir}/HypoElasticMaterialPanel.java

ICEInputsPanel: ICEInputsPanel.java
	${JAVAC} ${srcdir}/ICEInputsPanel.java 

ICEMaterialsPanel: ICEMaterialsPanel.java
	${JAVAC} ${srcdir}/ICEMaterialsPanel.java 

ICEMaterialInputPanel: ICEMaterialInputPanel.java
	${JAVAC} ${srcdir}/ICEMaterialInputPanel.java 

InputGeometryPanel: InputGeometryPanel.java
	${JAVAC} ${srcdir}/InputGeometryPanel.java 

InputPartDistPanel: InputPartDistPanel.java
	${JAVAC} ${srcdir}/InputPartDistPanel.java 

IntegerField: IntegerField.java
	${JAVAC} ${srcdir}/IntegerField.java

IntegerVectorField: IntegerVectorField.java
	${JAVAC} ${srcdir}/IntegerVectorField.java

LightWeightCanvas: LightWeightCanvas.java
	${JAVAC} ${srcdir}/LightWeightCanvas.java 

MPMContactInputPanel: MPMContactInputPanel.java
	${JAVAC} ${srcdir}/MPMContactInputPanel.java 

MPMInputsPanel: MPMInputsPanel.java
	${JAVAC} ${srcdir}/MPMInputsPanel.java 

MPMMaterialsPanel: MPMMaterialsPanel.java
	${JAVAC} ${srcdir}/MPMMaterialsPanel.java 

MPMMaterialInputPanel: MPMMaterialInputPanel.java
	${JAVAC} ${srcdir}/MPMMaterialInputPanel.java 

MPMICEExchangePanel: MPMICEExchangePanel.java
	${JAVAC} ${srcdir}/MPMICEExchangePanel.java

Packing: Packing.java
	${JAVAC} ${srcdir}/Packing.java 

ParticleGeneratePanel: ParticleGeneratePanel.java
	${JAVAC} ${srcdir}/ParticleGeneratePanel.java 

Particle: Particle.java
	${JAVAC} ${srcdir}/Particle.java 

ParticleList: ParticleList.java
	${JAVAC} ${srcdir}/ParticleList.java 

ParticleLocGeneratePanel: ParticleLocGeneratePanel.java
	${JAVAC} ${srcdir}/ParticleLocGeneratePanel.java 

ParticleSizeDistInputPanel: ParticleSizeDistInputPanel.java
	${JAVAC} ${srcdir}/ParticleSizeDistInputPanel.java 

ParticleSize: ParticleSize.java
	${JAVAC} ${srcdir}/ParticleSize.java 

Point: Point.java
	${JAVAC} ${srcdir}/Point.java 

PolygonDouble: PolygonDouble.java
	${JAVAC} ${srcdir}/PolygonDouble.java 

RigidMaterialPanel: RigidMaterialPanel.java
	${JAVAC} ${srcdir}/RigidMaterialPanel.java 

SmoothCylGeomPiece: SmoothCylGeomPiece.java
	${JAVAC} ${srcdir}/SmoothCylGeomPiece.java

TimeInputPanel: TimeInputPanel.java
	${JAVAC} ${srcdir}/TimeInputPanel.java

UintahGui: UintahGui.java
	${JAVAC} ${srcdir}/UintahGui.java 

UintahInputPanel: UintahInputPanel.java
	${JAVAC} ${srcdir}/UintahInputPanel.java 

UnionGeomPiece: UnionGeomPiece.java
	${JAVAC} ${srcdir}/UnionGeomPiece.java

VariableSaveInputPanel: VariableSaveInputPanel.java
	${JAVAC} ${srcdir}/VariableSaveInputPanel.java

Vector3D: Vector3D.java
	${JAVAC} ${srcdir}/Vector3D.java 

ViscoSCRAMMaterialPanel: ViscoSCRAMMaterialPanel.java
	${JAVAC} ${srcdir}/ViscoSCRAMMaterialPanel.java

Voronoi: Voronoi.java
	${JAVAC} ${srcdir}/Voronoi.java 

clean: 
	rm -f *.class

