#!/bin/csh -f
set savedir = $PWD
if(! -f $1/x.c) then
	 echo "static int _dummy_;" > $1/x.c
endif
(cd $1 && ls *.{c,cc}) > tmpl_cclist.new
if ( -f tmpl_cclist ) then
else
  touch tmpl_cclist
endif

diff tmpl_cclist tmpl_cclist.new > /dev/null
if ($status == 0)then
# No difference...
rm -f tmpl_cclist.new
goto built
endif

# Make a new makefile in $1
rm -f tmpl_cclist
mv tmpl_cclist.new tmpl_cclist
set m = $1"/Makefile"
rm -f $m
set tmpls=`cat tmpl_cclist`
echo "" > $m
echo "SRCS = \\" >> $m
awk '/^x.cc/ {printf("\t%s\n",$0);next;} {printf("\t%s \\\n", $0);}' < tmpl_cclist >> $m
echo "" >> $m
echo "" >> $m
echo "OBJS = \\" >> $m
sed -e 's/\.cc/.o/' -e 's/\.c/.o/' < tmpl_cclist | awk '/^x.o/ {printf("\t%s \n", $0);next} {printf("\t%s \\\n", $0);}' >> $m
echo "" >> $m
echo "" >> $m
echo "default: fast_templates.o" >> $m
echo "" >> $m
echo "x.o: x.c" >> $m
echo "	cc -c x.c" >> $m
echo "" >> $m
echo ".SUFFIXES: .cc" >> $m
echo ".cc.o: " >> $m
echo '	rm -f $@' >> $m
echo "" >> $m
echo 'fast_templates.o: $(OBJS)' >> $m
echo "	rm -f fast_templates.o" >> $m
#echo "	ar rc fast_templates.a *.o" >> $m
echo "	ld -r -o fast_templates.o *.o" >> $m
echo "" >> $m

(cd $1 && makedepend -s "# DO NOT DELETE" -- -I../lib -I../project/project -I../project/modules -I../wrapper -I../wrapper/Mt -I../wrapper/libMInT   -nostdinc -I/usr/include -DXML -DSYSV -DSVR4  -DFUNCPROTO=7 -DNARROWPROTO -DSCI_ASSERTIONS -I/usr/include/CC -- $tmpls )


built:
(cd $1 && make)
