function [A,ierr] = loadHypreIJMatrix(filename,numProcs)
%LOADHYPREIJMATRIX  Load sparse matrix from Hypre IJ output format.
%   A = LOADHYPREIJMATRIX(FNAME,NUMPROCS) loads the matrix A from multiple ouptut
%   files generated by Hypre, in IJ format. The Hypre matrix should be
%   printed to files using the following C commands in a Hypre interface:
%
%   HYPRE_ParCSRMatrix  par_A;
%   HYPRE_ParCSRMatrixPrintIJ(par_A, 1, 1, FNAME);
%
%   where FNAME is the same string as the input argument to this MATLAB
%   function. A is returned as a sparse MATLAB matrix. NUMPROCS is the
%   number of processors used to generate the Hypre output files.
%
%   See also: LOAD, LOADHYPREPARVECTOR.

% Revision history:
% 21-JUL-2005   Oren      Created


% Based on the Hypre function parcsr_mv/hypre_ParCSRMatrixReadIJ

o       = 1;
base_i  = 1;
base_j  = 1;
ierr    = 0;
parAlist = zeros(0,3);

for myid = 0:numProcs-1
    new_filename = sprintf('%s.%05d', filename, myid);
    file = fopen(new_filename, 'r');
    if (file < 0)
        fprintf('Error: can''t open output file %s\n', new_filename);
        A = [];
        ierr = 1;
        return;
    end

    global_num_rows     = fscanf(file, '%d',1);
    global_num_cols     = fscanf(file, '%d',1);
    num_rows            = fscanf(file, '%d',1);
    num_cols            = fscanf(file, '%d',1);
    num_cols_offd       = fscanf(file, '%d',1);
    num_nonzeros_diag   = fscanf(file, '%d',1);
    num_nonzeros_offd   = fscanf(file, '%d',1);

    row_starts          = zeros(numProcs+1,1);
    col_starts          = zeros(numProcs+1,1);

    for i = 0:numProcs
        row_starts(i+o) = fscanf(file, '%d',1);
        col_starts(i+o) = fscanf(file, '%d',1);
    end

    data = fscanf(file, '%d %d %e');
    Alist = reshape(data,[3 length(data)/3])';
    parAlist = [parAlist; Alist];
    fprintf('Loaded matrix from proc = %d\n',myid);
end  % for myid

A = sparse(parAlist(:,1),parAlist(:,2),parAlist(:,3));
