#!/bin/sh

TEST_UDADIR=$1
COMPARE_UDADIR=$2
SUS_DIR=$3

inputs_differ=0
echo
echo "*************************"
echo "Comparing $TEST_UDADIR with $COMPARE_UDADIR"
echo "*************************"
echo
echo "Checking input files"
echo
diff -B $TEST_UDADIR/input.xml $COMPARE_UDADIR/input.xml
if [ $? != "0" ]; then
    echo
    echo "  Input files differ."
    inputs_differ=1
else
    echo "  Input files are the same."
fi

failed="0"
echo
echo "Comparing dat files"
echo "======================================"
echo

compare_dats $TEST_UDADIR $COMPARE_UDADIR
compare_dats_retval=$?
if [ $compare_dats_retval = "1" ]; then
    echo 
    echo "*** dat comparison tests failed ***"
    failed="1"
elif [ $compare_dats_retval = "-1" ]; then
    failed="-1"
fi


echo
echo "Comparing udas"
echo "======================================"
echo
echo "$SUS_DIR/compare_uda $TEST_UDADIR $COMPARE_UDADIR"

$SUS_DIR/compare_uda $TEST_UDADIR $COMPARE_UDADIR
uda_retval=$?

if [ $uda_retval != "0" ]; then
    echo 
    echo "*** uda comparison tests failed ***"
    failed="1"
fi

echo
echo "Comparing checkpoints"
echo "======================================"
echo
echo "$SUS_DIR/compare_uda -skip_unknown_types $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints"

$SUS_DIR/compare_uda -skip_unknown_types $TEST_UDADIR/checkpoints $COMPARE_UDADIR/checkpoints
chp_retval=$?

if [ $chp_retval != "0" ]; then
    echo 
    echo "*** checkpoint comparison tests failed ***"
    failed="1"
fi

if [ $failed != "0" ]; then
    if [ $inputs_differ = "1" ]; then
        exit 5;
    fi
    exit $failed
fi

if [ $inputs_differ = "1" ]; then
    exit 10;
fi

exit 0

