#
#  The contents of this file are subject to the University of Utah Public
#  License (the "License"); you may not use this file except in compliance
#  with the License.
#  
#  Software distributed under the License is distributed on an "AS IS"
#  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
#  License for the specific language governing rights and limitations under
#  the License.
#  
#  The Original Source Code is SCIRun, released March 12, 2001.
#  
#  The Original Source Code was developed by the University of Utah.
#  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
#  University of Utah. All Rights Reserved.
#

# This is not the real makefile - there is a single top level
# makefile, at $(TOP).  The targets for this directory are
# specified in sub.mk in this directory
SRCTOP := @SRCTOP@
OBJTOP := @OBJTOP@
HERE_TARGET := @HERE_TARGET@

DEFAULT_TARGET ?= all

default:
	cd $(OBJTOP) && $(MAKE) --print-directory $(DEFAULT_TARGET)

here:
	@echo "Attempting to build in $(HERE), this might not work for all directories..."
	cd $(OBJTOP) && $(MAKE) --print-directory $(HERE_TARGET)

%:
	cd $(OBJTOP) && $(MAKE) --print-directory $@

