/* soapH.h
   Generated by gSOAP 2.6.2 from OQAFMA/OQAFMAClient.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

SOAP_BEGIN_NAMESPACE(soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, int, void*, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, void*, void*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, std::string const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_std__string(struct soap*, const std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns1__getClosure
#define SOAP_TYPE_ns1__getClosure (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getClosure(struct soap*, struct ns1__getClosure const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns1__getClosure(struct soap*, const struct ns1__getClosure *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getClosure(struct soap*, struct ns1__getClosure *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getClosure(struct soap*, const struct ns1__getClosure *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getClosure(struct soap*, const char*, int, const struct ns1__getClosure *, const char*);
SOAP_FMAC3 struct ns1__getClosure * SOAP_FMAC4 soap_get_ns1__getClosure(struct soap*, struct ns1__getClosure *, const char*, const char*);
SOAP_FMAC3 struct ns1__getClosure * SOAP_FMAC4 soap_in_ns1__getClosure(struct soap*, const char*, struct ns1__getClosure *, const char*);

SOAP_FMAC5 struct ns1__getClosure * SOAP_FMAC6 soap_new_ns1__getClosure(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getClosure(struct soap*, struct ns1__getClosure*);
SOAP_FMAC5 struct ns1__getClosure * SOAP_FMAC6 soap_instantiate_ns1__getClosure(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ns1__getClosureResponse
#define SOAP_TYPE_ns1__getClosureResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getClosureResponse(struct soap*, struct ns1__getClosureResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns1__getClosureResponse(struct soap*, const struct ns1__getClosureResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getClosureResponse(struct soap*, struct ns1__getClosureResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getClosureResponse(struct soap*, const struct ns1__getClosureResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getClosureResponse(struct soap*, const char*, int, const struct ns1__getClosureResponse *, const char*);
SOAP_FMAC3 struct ns1__getClosureResponse * SOAP_FMAC4 soap_get_ns1__getClosureResponse(struct soap*, struct ns1__getClosureResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getClosureResponse * SOAP_FMAC4 soap_in_ns1__getClosureResponse(struct soap*, const char*, struct ns1__getClosureResponse *, const char*);

SOAP_FMAC5 struct ns1__getClosureResponse * SOAP_FMAC6 soap_new_ns1__getClosureResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__getClosureResponse(struct soap*, struct ns1__getClosureResponse*);
SOAP_FMAC5 struct ns1__getClosureResponse * SOAP_FMAC6 soap_instantiate_ns1__getClosureResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ns1__processStruQL
#define SOAP_TYPE_ns1__processStruQL (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__processStruQL(struct soap*, struct ns1__processStruQL const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns1__processStruQL(struct soap*, const struct ns1__processStruQL *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__processStruQL(struct soap*, struct ns1__processStruQL *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__processStruQL(struct soap*, const struct ns1__processStruQL *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__processStruQL(struct soap*, const char*, int, const struct ns1__processStruQL *, const char*);
SOAP_FMAC3 struct ns1__processStruQL * SOAP_FMAC4 soap_get_ns1__processStruQL(struct soap*, struct ns1__processStruQL *, const char*, const char*);
SOAP_FMAC3 struct ns1__processStruQL * SOAP_FMAC4 soap_in_ns1__processStruQL(struct soap*, const char*, struct ns1__processStruQL *, const char*);

SOAP_FMAC5 struct ns1__processStruQL * SOAP_FMAC6 soap_new_ns1__processStruQL(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__processStruQL(struct soap*, struct ns1__processStruQL*);
SOAP_FMAC5 struct ns1__processStruQL * SOAP_FMAC6 soap_instantiate_ns1__processStruQL(struct soap*, int, const char*, const char*, size_t*);

#ifndef SOAP_TYPE_ns1__processStruQLResponse
#define SOAP_TYPE_ns1__processStruQLResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__processStruQLResponse(struct soap*, struct ns1__processStruQLResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns1__processStruQLResponse(struct soap*, const struct ns1__processStruQLResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__processStruQLResponse(struct soap*, struct ns1__processStruQLResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__processStruQLResponse(struct soap*, const struct ns1__processStruQLResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__processStruQLResponse(struct soap*, const char*, int, const struct ns1__processStruQLResponse *, const char*);
SOAP_FMAC3 struct ns1__processStruQLResponse * SOAP_FMAC4 soap_get_ns1__processStruQLResponse(struct soap*, struct ns1__processStruQLResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__processStruQLResponse * SOAP_FMAC4 soap_in_ns1__processStruQLResponse(struct soap*, const char*, struct ns1__processStruQLResponse *, const char*);

SOAP_FMAC5 struct ns1__processStruQLResponse * SOAP_FMAC6 soap_new_ns1__processStruQLResponse(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__processStruQLResponse(struct soap*, struct ns1__processStruQLResponse*);
SOAP_FMAC5 struct ns1__processStruQLResponse * SOAP_FMAC6 soap_instantiate_ns1__processStruQLResponse(struct soap*, int, const char*, const char*, size_t*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapH.h */
