#!/bin/csh
#______________________________________________________________________
#  Usage:  replace_XML_line <replacement Pattern> < filename>
#
#  This script reads in an XML file and replaces the line
#  who's xml tag matches the replacment pattern xml tag.
#______________________________________________________________________

set replacePattern = "$argv[1]"  # replacement pattern
set f              = $argv[2]  # filename

if ( $#argv != 2) then
  echo "Usage:  replace_XML_Line <replacement Pattern> < filename>
  exit
endif

if (! -e $f || ! -f $f) then  
  echo " file ($f) not found"
  echo "Usage:  replace_XML_Line <replacement Pattern> < filename>"
  exit
endif

# change </xmlTag>  to <\/xmlTag> so sed can use it
echo "$replacePattern"> .tmp
set replacePattern = `sed s/'\/'/"\\\/"/g .tmp`
/bin/rm .tmp


# find  xml tag
set xml_tag = `echo "$replacePattern" |awk -F"[<>]" '{print $2}'`
#echo "xml_tag: $xml_tag : replacePattern : $replacePattern"

#do a line replacement
cp $f $f.tmp

# bulletproofing
grep -q "<$xml_tag>.*<\/$xml_tag>" $f.tmp

if ($status != 0) then
  echo ""
  echo " Could not find the xml tags"
  echo " <$xml_tag>.*</$xml_tag>"
  echo " now exiting"
  exit 1
endif

# perform the replacement
sed s/"<$xml_tag>.*<\/$xml_tag>"/"$replacePattern"/g < $f.tmp >& $f


#bulletproofing
if ($status != 0) then
  echo ""
  echo "Error:  there was a problem during the search and replace."
  echo "        The original file has not been modified."
  echo ""
  mv $f.tmp $f
  exit 1
endif

#clean up
/bin/rm $f.tmp

exit 0
