#
# This is not the real makefile - there is a single top level
# makefile, at $(TOP).  The targets for this directory are
# specified in sub.mk in this directory
#
TOP := ../..

include $(TOP)/scripts/default.mk
