% Adapted from FDS' plotspec_uvw.m
% original may be found here:
% http://code.google.com/p/fds-smv/source/browse/trunk/FDS/trunk/Utilities/
% Matlab/scripts/plotspec_uvw.m
%
% function: plot_energy_spectrum_uda
% author: Tony Saad
% date: Sept 2012
%
% energy_spectrum_uda: calculates the turbulent kinetic energy spectrum given
% u, v, and w velocities. This specific routine takes data generated by
% using lineextract with Uintah's uda file format.
%
% Usage: From your uda archive, use lineextract and save the u, v, and w
% velocities into seperate files. Then, call this function with the
% respective u, v and w filenames generated by lineextract. You must also
% pass in the domain size L, assuming we have a box of equal sides.
% Finally, the symbol is a string denoting the symbol to use in this plot
%

function [k_nyquist] = plot_energy_spectrum_uda(uFileName, vFileName, wFileName, L, symbol)

  % load the data files
  uData = load(uFileName);
  vData = load(vFileName);
  wData = load(wFileName);

  % get the total size, n total: nt= nx * ny * nz
  nt = size(uData,1);

  % nx, ny, and nz are all equal
  n = round(nt^(1/3));

  % allocate memory for physical u, v, and w
  u = zeros(n,n,n);
  v = zeros(n,n,n);
  w = zeros(n,n,n);

  % extract the velocities from the datafiles generated by lineextract
  for p=1:nt
    i = uData(p,1) + 1;
    j = uData(p,2) + 1;
    k = uData(p,3) + 1;
    u(i,j,k) = uData(p,4);
    v(i,j,k) = vData(p,4);
    w(i,j,k) = wData(p,4);    
  end

  % calculate turbulent kinetic energy spectrum
  [wn, vt] = tke_spectrum(u,v,w,L);

  % plot the energy spectrum
  loglog(wn(2:n),vt(2:n),symbol,'MarkerSize',15);

  % return value
  k0 = 2*pi/L;
  k_nyquist = k0*n/2;

end