#!/bin/csh -f
#_________________________________________________________________________
#   This gnuplot script plots the total mass, momentum, kinetic energy and 
#   internal energy from the dat files.  You need to add
# 
#       <save label = "KineticEnergy"/>
#       <save label = "TotalMass"/>
#       <save label = "StrainEnergy"/>
#       <save label = "CenterOfMassPosition"/>
#       <save label = "TotalMomentum"/>
#   to the ups file.
#_________________________________________________________________________
#
if ($#argv == "0") then
  echo "Usage: plot_dat_files <path to uda>"
  exit
endif

set uda = $1;
if ( ! -d $uda ) then
  echo "ERROR:  path to uda is not valid"
  echo "Usage: plot_dat_files <path to uda>"
  exit
endif

echo $uda
#_________________________________
#  rip out "[" "]" from center of mass
sed 's/\[//g' $uda/TotalMomentum.dat | sed 's/\]//g' >$uda/TotalMom.dat

cat > gp << fin
set ytics
set xtics
set mxtics
set mytics
#set grid mxtics ytics
set grid xtics ytics
set pointsize 1
set format y "%10.3f"

set autoscale
set terminal x11 1
#set terminal postscript color "Times-Roman" 12
#set output "$uda/datPlots.ps"

set label "2-D pure translation test (XZ plane, 3 levels, RR:4, simple grid)" at screen 0.5, screen 0.99 center

#set xrange[0:0.02]
#__________________________________
#   TotalMass
#__________________________________
set multiplot
set size 0.50,0.48  
set origin 0.0,0.0
set ylabel "Total mass"
#set y2tics

plot   '$uda/TotalMass.dat'      using 1:2 t ''  w lines

#__________________________________
#   StrainEnergy
#__________________________________
set origin 0.5,0.0
#set yrange[-1e-3:1e-3]
set ylabel "Strain Energy"
plot   '$uda/StrainEnergy.dat'    using 1:2  t '' w lines

#__________________________________
#  KineticEnergy.dat
#__________________________________ 
set origin 0.0,0.5
#set yrange[3999.999:4000.001]
set ylabel "KineticEnergy"
plot   '$uda/KineticEnergy.dat'  using 1:2 t ''  w lines

#__________________________________
#  totalMomentum.dat
#__________________________________ 
set origin 0.5,0.48
#set yrange[6320 - 6320*0.0001:6320 + 6320*0.0001]
set ylabel "Total Momentum"
plot   '$uda/TotalMom.dat'         using 1:2 t 'x'  w linespoints,\
       '$uda/TotalMom.dat'         using 1:3 t 'y'  w linespoints, \
       '$uda/TotalMom.dat'         using 1:4 t 'z'  w linespoints
       
set nomultiplot   
pause -1 "Hit return to continue"

fin
#__________________________________
#   Now plot it up

gnuplot gp

exit
