#
# This is not the real makefile - there is a single top level
# makefile, at $(TOP).  The targets for this directory are
# specified in sub.mk in this directory
#
SRCTOP := @SRCTOP@
OBJTOP := @OBJTOP@
HERE_TARGET := @HERE_TARGET@

include $(OBJTOP)/$(SRCTOP)/scripts/default.mk
