#!/bin/csh

if ( $# != 1 ) then
   echo
   echo "Usage: $0 <matlab_file_name>"
   echo
   exit
endif


set ml_filename=$1

if ( ! -f $ml_filename ) then
   echo
   echo "Matlab input file $ml_filename does not exist!"
   echo
   exit
endif

set the_date=`date`
set the_short_date=`date +%m_%d_%Y`

echo "$the_date"
echo "$the_short_date"

set log_file="matlab_$the_short_date.log"
echo "log_file: $log_file"

if ( -f $log_file ) then
   echo
   echo "The log file '$log_file' already exists.  Replace it? (y/n)"
   set answer = $<
   echo "answer is $answer"
   if ( $answer == 'y' ) then
     rm -f $log_file
   else
     echo
     exit
   endif

endif

echo
echo "Running matlab7 with input file $ml_filename (please wait)..."
cat $ml_filename | matlab7 -nodisplay > & $log_file

# Save list of commands
rm -f temp
cat $ml_filename > temp
echo "--------------------------------------------------" >> temp
echo $the_date >> temp
echo "--------------------------------------------------" >> temp
cat $log_file >> temp

set MAIL_LIST=livne@sci.utah.edu
#set MAIL_LIST="livne@sci.utah.edu, wright@math.utah.edu"

mail $MAIL_LIST -s "PressSolve Run $the_short_date" < temp
rm -f temp
