#! /bin/bash
#
#  The MIT License
#
#  Copyright (c) 1997-2012 The University of Utah
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.
# 
# 
# 
# 
# 
#
export SCIRUN_OBJDIR=`echo $0 | awk -F/ '{ for (i = 1; i < NF; i++) printf("%s/",$i); printf("\n") }'`
export SCIRUN_OBJDIR=`cd ${SCIRUN_OBJDIR}; pwd`
export SCIRUN_SRCDIR=`cd ${SCIRUN_OBJDIR}/../src; pwd`
export SCIRUN_THIRDPARTY_DIR=`cd ${SCIRUN_OBJDIR}/../Thirdparty; pwd`
export SCIRUN_ITCL_WIDGETS=${SCIRUN_THIRDPARTY_DIR}/lib/iwidgets/scripts
export TCL_LIBRARY=${SCIRUN_THIRDPARTY_DIR}/lib/tcl
export SCIRUN_INSIGHT_LIB=${SCIRUN_THIRDPARTY_DIR}/lib/InsightToolkit
export DYLD_LIBRARY_PATH=${SCIRUN_THIRDPARTY_DIR}/lib:${SCIRUN_INSIGHT_LIB}:${SCIRUN_OBJDIR}/lib/
export DISPLAY=:0.0
if [ -d /Applications/Utilities/X11.app ]; then
    /usr/bin/open -a /Applications/Utilities/X11.app 
elif [ -d /Applications/X11.app ]; then
    /usr/bin/open -a /Applications/X11.app 
fi

${SCIRUN_OBJDIR}/scirun-bin >& /dev/null