#!/usr/local/bin/python

from sys import argv,exit
from helpers.runSusTests import runSusTests

TESTS = [   ("cyl_smag", "cyl_smag.ups", "", 1, "ALL"),	\
    	]

exit(runSusTests(argv, TESTS, "rmpmice"))
