#!/usr/bin/ruby
#
#  The contents of this file are subject to the University of Utah Public
#  License (the "License"); you may not use this file except in compliance
#  with the License.
#
#  Software distributed under the License is distributed on an "AS IS"
#  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
#  License for the specific language governing rights and limitations under
#  the License.
#
#  The Original Source Code is SCIRun, released March 12, 2001.
#
#  The Original Source Code was developed by the University of Utah.
#  Portions created by UNIVERSITY are Copyright (C) 2001, 1994
#  University of Utah. All Rights Reserved.
#

# Subroutines invoked by latex2html that generate begin and end <BODY>
# tags and code/text just after <BODY> and just before </BODY>.

sub my_start_body {
    return "<BODY $_[0]>\n"
	. "<SCRIPT src=\"" . $ENV{"TREETOP"} . "/doc/Utilities/HTML/tools.js\"></SCRIPT>\n"
	. "<SCRIPT>var doc=new Latex2HTMLDocument(); doc.preContent();</SCRIPT>\n";
}

sub my_end_body {
    return "<SCRIPT>doc.postContent();</SCRIPT>\n"
	. "</BODY>\n</HTML>\n";
}

$start_body = \&my_start_body;
$end_body = \&my_end_body;

1;
