#!/bin/bash

#______________________________________________________________________
#  This script performs bulletproofing checks and calls
#  the perl script (compare_dat_files.pl) which does the dat file comparisons.
# 
#   exit return values:
#     -1:   no dat files to compare
#      0:   The dat files are withn allowable errors
#      1:   Comparison failed
#      2:   Missing dat files
#______________________________________________________________________

tmpFile='.tmpCompDat'
test_uda=$1
gs_uda=$2

abs_tol=$3  # Absolute tolerance
rel_tol=$4  # Relative tolerance

if [ ! -d "$test_uda" ]; then
  echo "$test_uda doesn't exist"
  exit 1
fi  
if [ ! -d "$gs_uda" ]; then
  echo "$gs_uda doesn't exist"
  exit 1
fi

#__________________________________
#  are dat file present?
n_dats_uda=`find $test_uda -maxdepth 1 -type f -name '*.dat' | wc -l`
n_dats_gs=`find $gs_uda -maxdepth 1 -type f -name '*.dat' | wc -l`
sum=$((n_dats_uda + n_dats_gs))

if [ $sum == 0 ]; then
  echo "  No dat files to compare"
  exit -1
fi

#__________________________________
# do both udas have dat files?

diff $test_uda $gs_uda | grep -E 'Only.*dat' > $tmpFile

missing_dats=`wc --lines < $tmpFile`

if [ ${missing_dats} != "0" ]; then
  
  dats=`cat $tmpFile | grep $test_uda | cut -f 2 -d :`
  
  if [ ! -z $dats ]; then
    echo "   ERROR: Missing dat files ($dats) in the gold standard uda"
    exit 2
  fi
  
  dats=`cat $tmpFile | grep $gs_uda | cut -f 2 -d :`  
  
  if [ ! -z $dats  ]; then
    echo "   ERROR: Missing dat files ($dats) in the gold standard uda"
    exit 2 
  fi
fi
/bin/rm $tmpFile

#__________________________________
# perform comparison
WD=`pwd`
cd $test_uda
dats=`ls -1 *.dat`
testdat=`ls -1 *.dat | head -n 1`
cd $WD

compare_dat_files.pl $abs_tol $rel_tol $test_uda/ $gs_uda/ $dats

retval=$?

exit $retval

