#!/bin/bash

test=$1
test_dir=$2
compare_root=$3
sus_dir=$4
abs_tol=$5 # Absolute tolerance 
rel_tol=$6 # Relative tolerance

wd=`pwd`
cd $test_dir
udadir=`ls -d *.uda`
cd $wd
command
test_udadir=$test_dir/$udadir
compare_udadir=$compare_root/$test/$udadir


if [ -d "$test_udadir" ]; then
  if [ ! -d "$compare_root" ]; then
    echo "Creating $compare_root directory"
    compare_PARENT_DIR=`echo "$compare_root" | sed 's|/[^/]*$||'`
    cd $compare_PARENT_DIR
    compare_DIR=`echo "$compare_root" | sed "s|.*/||"`
    mkdir $compare_DIR
#    cvs add $compare_DIR
  fi
  if [ ! -d "$compare_root/$test" ]; then
    echo "Creating $compare_root/$test directory"
    cd $compare_root
    mkdir $test
#    cvs add $test
  fi
  if [ ! -d "$compare_udadir" ]; then
    echo "Storing uda directory: $compare_udadir"

    # try to remove it in case it exists as a non-directory
    /bin/rm $compare_udadir 

    # if cp has a --dereference option, then us it
    cp -r --dereference $test_udadir $compare_udadir
    if [ $? != "0" ]; then
	# try without --dereference -- not all cp's have this option
	cp -r $test_udadir $compare_udadir
    fi
    
    # copy text files to the goldStandard
    cp $test_dir/sus.log.txt  $test_dir/timestamp $test_dir/restart_timestamp $compare_root/$test >/dev/null 2>&1
    cp $test_dir/malloc_stats $test_dir/restart_malloc_stats $compare_root/$test >/dev/null 2>&1

    chgrp -R $COMMON_GROUP "$compare_root/$test"
    chmod -R g+rwX "$compare_root/$test"

    exit -2
    
  else
      echo "Testing $test"
      compare_sus_runs_by_udas $test_udadir $compare_udadir $sus_dir $abs_tol $rel_tol
      exit $?
  fi
else
  echo "$test_udadir was not created"
  exit 1
fi

exit 0

