#!/bin/sh

# $BUILD_DIR $BUILDROOT, $HTMLLOG, $NOTESTS, $PARALLELISM, $COMPILE, and $MAKE_PARALLELISM must be set

mode=$1 # dbg or opt

WithArches="yes"

export WithArches
retval=0

if [ "$COMPILE" = "yes" ]; then
  # create the build directory 
  if [ ! -d "${BUILDROOT}/${mode}/build" ]; then
    mkdir "${BUILDROOT}/${mode}/build"
  fi
  cd "${BUILDROOT}/${mode}/build"

  # configure and compile the code
  build $mode
  retval=$?
  
  #change the permissions
  echo "Changing permissions in `pwd`"
  chgrp -R csafe .
  chmod -R g+rwX . 
fi

#__________________________________
#  Run the tests
if [ "$retval" = "0" -a "$NOTESTS" = "0" ]; then
  run $1
  retval=$?
#  chmod -R a+rX "$HTMLLOG"-"$mode"
  exit $retval
else
  exit $retval
fi
