function [x,ierr] = loadHypreParVector(filename,numProcs)
%LOADHYPREPARVECTOR  Load parallel vector from Hypre.
%   X = LOADHYPREPARVECTOR(FNAME,NUMPROCS) loads the vector x from multiple ouptut
%   files generated by Hypre, in Par format. The Hypre matrix should be
%   printed to files using the following C commands in a Hypre interface:
%
%   HYPRE_ParVector  par_x;
%   HYPRE_ParVectorPrint(par_x, FNAME);
%
%   where FNAME is the same string as the input argument to this MATLAB
%   function. A is returned as a sparse MATLAB matrix. NUMPROCS is the
%   number of processors used to generate the Hypre output files.
%
%   See also: LOAD, LOADHYPREIJMATRIX.

% Revision history:
% 27-JUL-2005   Oren      Created


% Based on the Hypre functions
%   parcsr_mv/par_vector.c:hypre_ParVectorRead()
%   seq_mv/vector.c:hypre_SeqVectorRead()

o       = 1;
base_i  = 1;
base_j  = 1;
ierr    = 0;
parAlist = zeros(0,3);

% Read partition of vector from info file into the array partitioning
% All info files are the same, it seems. So use only the one for myid = 0.
my_id = 0;
new_filename = sprintf('%s.INFO.%d',filename,my_id);
file = fopen(new_filename, 'r');
if (file < 0)
    fprintf('Error: can''t open output info file %s\n', new_filename);
    x = [];
    ierr = 1;
    return;
end
partitioning = zeros(numProcs+1,1);
global_size = fscanf(file, '%d\n', 1);
for i = 0:numProcs-1
    partitioning(i+o) = fscanf(file, '%d\n', 1);
end
partitioning(numProcs+o) = global_size;
fclose(file);
fprintf('Loaded vector info\n');

x = zeros(global_size,1);
% Read data from data files into the vector x
for my_id = 0:numProcs-1
    new_filename = sprintf('%s.%d',filename,my_id);
    file = fopen(new_filename, 'r');
    if (file < 0)
        fprintf('Error: can''t open output data file %s\n', new_filename);
        x = [];
        ierr = 2;
        return;
    end
   sz = fscanf(file, '%d', 1);
   xPart = fscanf(file, '%e', sz);
   fclose(file);

   % Add the part of this processor to the global x
   firstIndex = partitioning(my_id+o);
   x(firstIndex+o:firstIndex+sz-1+o) = xPart;
   fprintf('Loaded vector from proc = %d\n',my_id);
end  % for myid
