#!/bin/sh

# remove old locks
for BUILDROOT in SCIRun.*; do
  if [ -d "$BUILDROOT" ]; then
    if [ -f "$BUILDROOT/lock" ]; then
      rm $BUILDROOT/lock
    fi
  fi
done

# create locks where *.lock files have symbolic links to
for lock in *.lock; do
  if [ -d "$lock" ]; then
    echo "locked" > "$lock"/lock
  fi
done

# delete all SCIRun.* directories that aren't locked
for BUILDROOT in SCIRun.*; do
  if [ -d "$BUILDROOT" ]; then
    if [ ! -f "$BUILDROOT/lock" ]; then
      cd "$BUILDROOT"
      echo "y" | /usr/local/bin/cvs release -d SCIRun > /dev/null 2>&1
      cd ".."
      rm -rf "$BUILDROOT"
    fi
  fi
done
