#!/bin/sh

# should have PATH, OS, PARALLISM, TMPDIR, BUILD_DIR, 
# BUILDROOT, TEST_DATA, OPT_CONFIGURE, and DBG_CONFIGURE all set
PATH="$BUILDROOT"/src/Packages/Uintah/Test/helpers:"$PATH"
export PATH OS MAKE_PARALLELISM PARALLELISM TMPDIR BUILD_DIR BUILDROOT TEST_DATA

echo "" >> "$BUILDROOT"/log

if [ ! -d "$BUILDROOT"/dbg ]; then
  mkdir "$BUILDROOT"/dbg
fi
if [ ! -d "$BUILDROOT"/opt ]; then
  mkdir "$BUILDROOT"/opt
fi

failed=0
build_and_run "dbg" "$DBG_CONFIGURE" > "$BUILDROOT"/dbg/log 2>&1
if [ $? != 0 ]; then
  failed=1
  echo "*** Some dbg tests failed." >> "$BUILDROOT"/log
fi

build_and_run "opt" "$OPT_CONFIGURE" > "$BUILDROOT"/opt/log 2>&1
if [ $? != 0 ]; then
  failed=1
  echo "*** Some opt tests failed." >> "$BUILDROOT"/log
fi

if [ $failed == "0" ]; then
  echo "All tests passed!" >> "$BUILDROOT"/log
fi

echo "" >> "$BUILDROOT"/log
echo "Debug build log:" >> "$BUILDROOT"/log
cat "$BUILDROOT"/dbg/log >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
echo "Optimized build log:" >> "$BUILDROOT"/log
cat "$BUILDROOT"/opt/log >> "$BUILDROOT"/log

# build_and_run should write summare-log files
if [ -f "$BUILDROOT"/dbg/summary-log ]; then
    echo "Summary for dbg mode tests:" >> "$BUILDROOT"/log
    echo "" >> "$BUILDROOT"/log
    cat "$BUILDROOT"/dbg/summary-log >> "$BUILDROOT"/log
fi
if [ -f "$BUILDROOT"/opt/summary-log ]; then
    echo "Summary for opt mode tests:" >> "$BUILDROOT"/log
    echo "" >> "$BUILDROOT"/log
    cat "$BUILDROOT"/opt/summary-log >> "$BUILDROOT"/log
fi
echo "" >> "$BUILDROOT"/log

/bin/chgrp -Rh csafe "$BUILDROOT"
/bin/chmod g+ws "$BUILDROOT"

if [ "$SEND_MAIL_TO" != "" ]; then
    if [ $failed == "0" ]; then
	subject="Successful regression tests on `hostname`"
    else
	subject="***Regression test failure on `hostname`***"
    fi

    cat > "$BUILDROOT"/mail.msg <<EOF
Subject: $subject
To: $SEND_MAIL_TO
EOF
    cat "$BUILDROOT"/log >> "$BUILDROOT"/mail.msg

     /usr/lib/sendmail "$SEND_MAIL_TO" < "$BUILDROOT"/mail.msg
    rm -f "$BUILDROOT"/mail.msg
fi

cat "$BUILDROOT"/log

if [ $failed == "0" ]; then
    if [ -d "${BUILD_DIR}/last_successful.lock" ]; then
	rm -r "${BUILD_DIR}/last_successful.lock" 
    fi
    ln -s "$BUILDROOT" "${BUILD_DIR}/last_successful.lock"
fi

cd "$BUILDROOT"
cleanup

exit $failed
