#!/bin/sh

# should have PATH, OS, PARALLISM, TMPDIR, BUILD_DIR, 
# BUILDROOT, TEST_DATA, OPT_CONFIGURE, and DBG_CONFIGURE all set
PATH="$BUILDROOT"/src/Packages/Uintah/Test/helpers:"$PATH"
export PATH OS MAKE_PARALLELISM PARALLELISM TMPDIR BUILD_DIR BUILDROOT TEST_DATA

echo "" >> "$BUILDROOT"/log

if [ ! -d "$BUILDROOT"/dbg ]; then
  mkdir "$BUILDROOT"/dbg
fi
if [ ! -d "$BUILDROOT"/opt ]; then
  mkdir "$BUILDROOT"/opt
fi

failed=0
dbg_failed=0
opt_failed=0
build_and_run "dbg" "$DBG_CONFIGURE" > "$BUILDROOT"/dbg/log 2>&1
if [ $? != 0 ]; then
  failed=1
  dbg_failed=1
fi

build_and_run "opt" "$OPT_CONFIGURE" > "$BUILDROOT"/opt/log 2>&1
if [ $? != 0 ]; then
  failed=1
  opt_failed=1
fi

if [ $failed == "0" ]; then
  echo "All tests passed!" >> "$BUILDROOT"/log
fi

echo "" >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
    echo "/--------------------------\\" >> "$BUILDROOT"/log
if [ $dbg_failed != "0" ]; then
    echo "| DEBUG TESTS - failed     |" >> "$BUILDROOT"/log
else
    echo "| DEBUG TESTS - passed     |" >> "$BUILDROOT"/log
fi
    echo "\\--------------------------/" >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
cat "$BUILDROOT"/dbg/log >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
    echo "/--------------------------\\" >> "$BUILDROOT"/log
if [ $opt_failed != "0" ]; then
    echo "| OPTIMIZED TESTS - failed |" >> "$BUILDROOT"/log
else
    echo "| OPTIMIZED TESTS - passed |" >> "$BUILDROOT"/log
fi
    echo "\\--------------------------/" >> "$BUILDROOT"/log
echo "" >> "$BUILDROOT"/log
cat "$BUILDROOT"/opt/log >> "$BUILDROOT"/log

# build_and_run should write summary_log files
if [ -f "$BUILDROOT"/dbg/summary_log ]; then
    echo "" >> "$BUILDROOT"/log
    echo "/--------------------------\\" >> "$BUILDROOT"/log
    echo "|    DEBUG TEST SUMMARY    |" >> "$BUILDROOT"/log
    echo "\\--------------------------/" >> "$BUILDROOT"/log
    echo "" >> "$BUILDROOT"/log
    cat "$BUILDROOT"/dbg/summary_log >> "$BUILDROOT"/log
fi
if [ -f "$BUILDROOT"/opt/summary_log ]; then
    echo "" >> "$BUILDROOT"/log
    echo "/--------------------------\\" >> "$BUILDROOT"/log
    echo "|  OPTIMIZED TEST SUMMARY  |" >> "$BUILDROOT"/log
    echo "\\--------------------------/" >> "$BUILDROOT"/log
    cat "$BUILDROOT"/opt/summary_log >> "$BUILDROOT"/log
fi
echo "" >> "$BUILDROOT"/log

/usr/local/gnu/bin/chgrp -Rh csafe "$BUILDROOT"
/usr/local/gnu/bin/chmod -R g+ws "$BUILDROOT"
/usr/local/gnu/bin/chgrp -Rh csafe "$TEST_DATA"
/usr/local/gnu/bin/chmod -R g+ws "$TEST_DATA"

if [ "$SEND_MAIL_TO" != "" ]; then
    if [ $failed == "0" ]; then
	subject="Successful regression tests on `hostname`"
    else
	subject="***Regression test failure on `hostname`***"
    fi

    cat > "$BUILDROOT"/mail.msg <<EOF
Subject: $subject
To: $SEND_MAIL_TO
EOF
    cat "$BUILDROOT"/log >> "$BUILDROOT"/mail.msg

     /usr/lib/sendmail "$SEND_MAIL_TO" < "$BUILDROOT"/mail.msg
    rm -f "$BUILDROOT"/mail.msg
fi

cat "$BUILDROOT"/log

if [ $failed == "0" ]; then
    if [ -d "${BUILD_DIR}/last_successful.lock" ]; then
	rm -r "${BUILD_DIR}/last_successful.lock" 
    fi
    ln -s "$BUILDROOT" "${BUILD_DIR}/last_successful.lock"
fi

cd "$BUILD_DIR"
cleanup

exit $failed
