#! /bin/bash

THELIB=ExprLib

source ../HelperBuildScripts/setupEnv.sh

rm -f CMakeCache.txt
rm -rf ${INSTALL_HERE}/*

/uufs/chpc.utah.edu/sys/pkg/cmake/2.8.9/bin/cmake \
  -DENABLE_TESTS=OFF                              \
                                                  \
  -DSpatialOps_DIR=$INSTALL_BASE/SpatialOps/$COMP/share \
                                                  \
  -DENABLE_UINTAH=ON                              \
                                                  \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE}          \
  -DCMAKE_C_COMPILER=$CC                          \
  -DCMAKE_CXX_COMPILER=$CXX                       \
  -DCMAKE_CXX_FLAGS="-fPIC"                       \
  .

if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "ExprLib: Updating installation permissions for ${INSTALL_HERE}..."
  chmod -R go+rX ${INSTALL_HERE}
fi

