#!/bin/csh -f
#__________________________________
#  This script pulls out data from sus 
#   output and plots it using gnuplot.
#  Usage:
#     plot_1LvsML <uda> <dump postScript File (y/Y), default is no>
#__________________________________

#set echo  for debugging scripts 
unalias rm
if( $#argv == 0 ) then
  echo "plot_1LvsML <uda 1L> <uda 2L> <dump postScript File (y/Y), default is no>"
  exit(1)
endif


set uda_1L = $argv[1]
set uda_2L = $argv[2]

if ( !(-e $uda_1L) || !(-e $uda_2L ) ) then
  echo "Couldn't find your uda $uda $uda2L"
  exit(1)
endif


set tmp = (`which lineextract` `which puda`)

if ( $status ) then
  echo " ERROR: Could not find one of the following Uintah utilities"
  echo "    lineextract"
  echo "    puda"
  exit(0)
endif

set hardcopy = "n"
if ( $#argv == 3 ) then
  set hardcopy = $argv[3]
endif 

#__________________________________
# which the timestep to plot
set ts =  (`puda -timesteps $uda_1L | grep : | cut -f 2 -d":"`)
set ts2 = (`puda -timesteps $uda_2L | grep : | cut -f 2 -d":"`)

echo "----------------------"
echo "        $uda_1L      $uda_2L"

@ c = 0
@ c2 = 1
foreach X ( $ts[*]:q ) 
  echo "$c) $X $ts2[$c2]"
  @ c  = $c + 1
  @ c2 = $c2 + 1
end 

echo "----------------------"
echo "What timestep would you like to plot?"
set timeStep = $<


# cell indices    HARDWIRED
set start = "0 4 4"
set end   = "1000 4 4"

@ XDIR  = 1
@ COL   = $XDIR + 3                 # x = 1, y = 2, z = 3

#__________________________________
# ExtractData from the data file
# coarse Level data
lineextract -cellCoords -istart $start -iend $end -v g.externalforce      -timestep $timeStep -uda $uda_1L -o gEF.1L.dat        
lineextract -cellCoords -istart $start -iend $end -v g.mass               -timestep $timeStep -uda $uda_1L -o gMass.1L.dat    
lineextract -cellCoords -istart $start -iend $end -v g.velocity           -timestep $timeStep -uda $uda_1L -o gVel.1L.dat  
lineextract -cellCoords -istart $start -iend $end -v g.acceleration       -timestep $timeStep -uda $uda_1L -o gAcc.1L.dat   
lineextract -cellCoords -istart $start -iend $end -v g.velocity_star      -timestep $timeStep -uda $uda_1L -o gVelStar.1L.dat   
lineextract -cellCoords -istart $start -iend $end -v g.internalforce      -timestep $timeStep -uda $uda_1L -o gIntF.1L.dat

#Level-1 data
lineextract -cellCoords -istart $start -iend $end -v g.externalforce -l 0 -timestep $timeStep -uda $uda_2L -o gEF.2L.0.dat
lineextract -cellCoords -istart $start -iend $end -v g.mass          -l 0 -timestep $timeStep -uda $uda_2L -o gMass.2L.0.dat
lineextract -cellCoords -istart $start -iend $end -v g.velocity      -l 0 -timestep $timeStep -uda $uda_2L -o gVel.2L.0.dat
lineextract -cellCoords -istart $start -iend $end -v g.acceleration  -l 0 -timestep $timeStep -uda $uda_2L -o gAcc.2L.0.dat
lineextract -cellCoords -istart $start -iend $end -v g.velocity_star -l 0 -timestep $timeStep -uda $uda_2L -o gVelStar.2L.0.dat
lineextract -cellCoords -istart $start -iend $end -v g.internalforce -l 0 -timestep $timeStep -uda $uda_2L -o gIntF.2L.0.dat

#Level-2 data
lineextract -cellCoords -istart $start -iend $end -v g.externalforce -l 1 -timestep $timeStep -uda $uda_2L -o gEF.2L.1.dat
lineextract -cellCoords -istart $start -iend $end -v g.mass          -l 1 -timestep $timeStep -uda $uda_2L -o gMass.2L.1.dat
lineextract -cellCoords -istart $start -iend $end -v g.velocity      -l 1 -timestep $timeStep -uda $uda_2L -o gVel.2L.1.dat
lineextract -cellCoords -istart $start -iend $end -v g.acceleration  -l 1 -timestep $timeStep -uda $uda_2L -o gAcc.2L.1.dat
lineextract -cellCoords -istart $start -iend $end -v g.velocity_star -l 1 -timestep $timeStep -uda $uda_2L -o gVelStar.2L.1.dat
lineextract -cellCoords -istart $start -iend $end -v g.internalforce -l 1 -timestep $timeStep -uda $uda_2L -o gIntF.2L.1.dat

scripts/removeBraces gEF.1L.dat       gEF.2L.0.dat      gEF.2L.1.dat
scripts/removeBraces gVel.1L.dat      gVel.2L.0.dat     gVel.2L.1.dat
scripts/removeBraces gAcc.1L.dat      gAcc.2L.0.dat     gAcc.2L.1.dat
scripts/removeBraces gVelStar.1L.dat  gVelStar.2L.0.dat gVelStar.2L.1.dat
scripts/removeBraces gIntF.1L.dat     gIntF.2L.0.dat    gIntF.2L.1.dat

/bin/rm -f gp

#__________________________________
# if making a hardcopy
if( $hardcopy == "y" || $hardcopy == "Y" ) then 
echo "Generating the postscript file 1LvsML.ps"
cat > gp << fin
set terminal postscript color solid "Times-Roman" 9 portrait
set output "1LvsML.ps"
fin
else
cat >gp << fin
set term png enhanced font '/usr/share/fonts/truetype/ttf-liberation/LiberationSans-Regular.ttf' 9 size 1400,900
set output '| display png:-'
fin
endif

#__________________________________
# generate the  plot script
cat >> gp << fin

set ytics
set xtics
set grid xtics ytics
set pointsize 1.0
set title ""

set autoscale
set multiplot
set size 1.0,0.25 
set origin 0.0,0.0
set key off

#__________________________________
#   g.externalForce
#__________________________________

set ylabel "g.externalForce"
set xrange [0:1]

xdir= `echo $XDIR`
col= `echo $COL`

plot  'gEF.1L.dat'            using xdir:col t '1 L',\
      'gEF.2L.0.dat'          using xdir:col t 'L-1',\
      'gEF.2L.1.dat'          using xdir:col t 'L-2'

#__________________________________
#   gmass
#__________________________________
set origin 0.0,0.25

set ylabel "gMass"
plot  'gMass.1L.dat'          using xdir:col t '1 L',\
      'gMass.2L.0.dat'        using xdir:col t 'L-1',\
      'gMass.2L.1.dat'        using xdir:col t 'L-2'

#__________________________________
#  gVelocity
#__________________________________
set origin 0.0,0.5

set ylabel "gVelocity"
plot  'gVel.1L.dat'            using xdir:col t '1 L',\
      'gVel.2L.0.dat'          using xdir:col t 'L-1',\
      'gVel.2L.1.dat'          using xdir:col t 'L-2'
#__________________________________
#   gAcceleration
#__________________________________
set origin 0.0,0.75
set key on 
set ylabel "gAccel"
plot  'gAcc.1L.dat'            using xdir:col t '1 L',\
      'gAcc.2L.0.dat'          using xdir:col t 'L-1',\
      'gAcc.2L.1.dat'          using xdir:col t 'L-2'
      
      
set nomultiplot 
pause -1 "Hit return to continue"
fin
#__________________________________
# plot it up
gnuplot gp


#__________________________________
# clean up
rm -f gp  *L.dat *.*.dat
