#!/bin/bash

# BUILDROOT, VERBOSE need to be set

# remove old locks
for BUILDROOT in SCIRun.*; do
  if [ -d "$BUILDROOT" ]; then
    if [ -f "$BUILDROOT/lock" ]; then
      rm $BUILDROOT/lock
    fi
  fi
done

# create locks where *.lock files have symbolic links to
for lock in *.lock; do
  if [ -d "$lock" ]; then
    echo "locked" > "$lock"/lock
  fi
done

if [ ! -d "trash" ]; then
  mkdir trash
fi

# delete all SCIRun.* directories that aren't locked
# -- move them to the trash directory first
for BUILDROOT in SCIRun.*; do
  if [ -d "$BUILDROOT" ]; then
    if [ ! -f "$BUILDROOT/lock" ]; then
      cd "$BUILDROOT"
      echo "y" | /usr/local/bin/cvs release -d SCIRun > /dev/null 2>&1
      cd ".."
      mv "$BUILDROOT" trash/.
    fi
  fi
done

# delete whatever can be deleted from the trash before adding to it
rm -rf trash > /dev/null 2>&1

if [ ! -d "trash" ]; then
  exit 0 # cleanup was successful
fi

find trash \( ! -user `id -un` \) -prune > trash/need_removal

if [ "$VERBOSE" = "yes" ]; then
    echo "Folders need to be removed by their owner:"
    echo ""
    cat trash/need_removal | xargs ls -ld
fi

# I'm sure there is a better way to get at the user names, but I've spent
# too much time trying to figure it out.
cat trash/need_removal | xargs ls -ld | awk '{ print $3 }' | sort -u > trash/usernames

for username in `cat trash/usernames`; do
    sendto=${username}@sci.utah.edu
    cat > trash/userRemoval <<EOF
Subject: Cleanup needed for regression tester
To: $sendto

This is an automated e-mail.
Please remove the following directories in order to clean out the regression tester.

Under `pwd` on `hostname`:

EOF
     find trash -user $username -prune -exec echo "rm -rf `pwd`/{}" \; >> trash/userRemoval    
    sendmail $sendto < trash/userRemoval
    rm trash/userRemoval
done

#cat trash/uids | xargs -i{UID} find trash -user {UID} -prune > trash/uid{UID}


