#!/usr/bin/python

from sys import argv,exit
from os import environ
from helpers.runSusTests import runSusTests

#______________________________________________________________________
#  Test syntax: ( "folder name", "input file", # processors, "OS", ["flags1","flag2"])
#  flags: 
#       no_uda_comparison:      - skip the uda comparisons
#       no_memoryTest:          - skip all memory checks
#       no_restart:             - skip the restart tests
#       no_dbg:                 - skip all debug compilation tests
#       no_opt:                 - skip all optimized compilation tests
#       do_performance_test:    - Run the performance test
#       doesTestRun:            - Checks if a test successfully runs
#       abs_tolerance=[double]  - absolute tolerance used in comparison
#       rel_tolerance=[double]  - relative tolerance used in comparison
#       exactComparison         - set absolute/relative tolerance = 0  for uda comparisons
#       startFromCheckpoint     - start test from checkpoint. (/usr/local/home/csafe-tester/CheckPoints/..../testname.uda.000)
#
#  Note: the "folder name" must be the same as input file without the extension.
#______________________________________________________________________

UNUSED = [ ("4disks2matsv", "4disks_2d.2matsv.ups", 4, "Linux"), \
    	]

NIGHTLYTESTS = [  ("4disks_2d.1mat",   "4disks_2d.1mat.ups", 1,   "None"), \
	           ("billet.static",    "billet.static.ups",  2,   "ALL"), \
	           ("adiCuJC01s296K",   "adiCuJC01s296K.ups", 1.1, "ALL"), \
	           ("adiCuMTS01s296K",  "adiCuMTS01s296K.ups",1.1, "ALL"), \
	           ("adiCuPTW01s296K",  "adiCuPTW01s296K.ups",1.1, "ALL"), \
	           ("adiCuSCG01s296K",  "adiCuSCG01s296K.ups",1.1, "ALL"), \
	           ("adiCuZA01s296K",   "adiCuZA01s296K.ups", 1.1, "ALL")
    	         ]
                
# Tests that are run during local regression testing       
LOCALTESTS = [    ("4disks_2d.1mat",   "4disks_2d.1mat.ups", 1,   "None"), \
	           ("billet.static",    "billet.static.ups",  2,   "ALL"), \
	           ("adiCuJC01s296K",   "adiCuJC01s296K.ups", 1.1, "ALL"), \
	           ("adiCuMTS01s296K",  "adiCuMTS01s296K.ups",1.1, "ALL"), \
	           ("adiCuPTW01s296K",  "adiCuPTW01s296K.ups",1.1, "ALL"), \
	           ("adiCuSCG01s296K",  "adiCuSCG01s296K.ups",1.1, "ALL"), \
	           ("adiCuZA01s296K",   "adiCuZA01s296K.ups", 1.1, "ALL")
    	       ]       

#__________________________________
if environ['LOCAL_OR_NIGHTLY_TEST'] == "local":
  TESTS = LOCALTESTS
else:
  TESTS = NIGHTLYTESTS
  
exit(runSusTests(argv, TESTS, "IMPM"))
