#!/bin/csh
#__________________________________
# This script stitches 2 folders of ppms together
# All of the images need to be the same size, so you 
# should use ppm_to_mpg to resize and add labels.      
       
       
set size = "640x480"  # size of a single image

set dir1 = "SC_FRAMES"    #path to ppms that you want on the left half
set dir2 = "GP_FRAMES"    #path to ppms that you want on the right half

@ timestep = 0
foreach T ( $dir1/*.ppm )
 set num = `printf '%04d' $timestep`
 echo "working on ppm # " $num
 montage -geometry $size $dir1/movie.$num.ppm $dir2/movie.$num.ppm movie.$num.ppm
 @ timestep = $timestep + 1
end
