#!/bin/csh -f
#______________________________________________________________________
# cpu_vs_gpu
#  This scripts runs an input file using both GPU and CPU code and
#  uses compare_uda to compare the results
#
#  This script assumes that 
#______________________________________________________________________

getopt -Q -q --long np,nthreads,test,tolerance -- $argv:q >& /dev/null

if (0) then
if($#argv != 6) then
  echo "Usage: $0 "
  echo ""
  echo " Manditory inputs:"
  echo "   --np           < number of processors >"
  echo "   --nthreads     < number of threads    >"
  echo "   --tolerance    < tight or loose >"
  echo "   --test         < (1) = Benchmark 1, 1L, "
  echo "                   (2) = Benchmark 1, 2L, "
  echo "                   (3) = Benchmark 1, DataOnion"
  echo "                   (4) = Arches/RMCRT/rmcrt_bm1_DO.ups"
  echo "                   (5) = all tests"
  exit 1
endif
endif
#______________________________________________________________________

while ($#argv)
   echo $1 $2

   switch ($1:q)

     case --np:
        @ np = $2
        shift; shift;
        breaksw
     case --nthreads:
        @ threads = "$2"
        shift; shift
        breaksw
     case --tolerance:
        if( "$2" == "loose") then
          set absTol = "0.05"
          set relTol = "1e-6"
        else
          set absTol = "1e-14"
          set relTol = "1e-14"       
        endif
        shift; shift
        breaksw
     case --test:
        @ test = "$2"
        shift; shift
        breaksw
     case " ":
        shift
        break
     default:
        echo "Usage: $0 "
        echo ""
        echo " Manditory inputs:"
        echo "   --np           < number of processors >"
        echo "   --nthreads     < number of threads    >"
        echo "   --tolerance    < tight or loose >"
        echo "                    Loose tolerance requires 256 rays per cell if using random number generator"
        echo "   --test        < (1) = 1L, "
        echo "                   (2) = 2L, "
        echo "                   (3) = dataOnion"
        echo "                   (4) = Arches/RMCRT/rmcrt_bm1_DO.ups"
        echo "                   (5) = all tests"
        exit 1
  endsw
end

#______________________________________________________________________
@ maxTests = 5

set upsArray = ( "inputs/Examples/RMCRT_bm1_1L.ups"\
                  "inputs/Examples/RMCRT_ML.ups"\
                  "inputs/Examples/RMCRT_bm1_DO.ups"\
                  "inputs/ARCHES/RMCRT/rmcrt_bm1_DO.ups" )
                  
set udaArray = ( "rmcrt_1L.uda" "RMCRT_ML.uda" "RMCRT_bm1_DO.uda" "rmcrt_bm1_DO.uda" )
set descArray = ( "1L" "ML" "DO" "ArchesDO")

# Titan
#set MPIRUN = "aprun -n $np -N 1 -d 16"

set MPIRUN = "mpirun -n $np" 

if ( $test == $maxTests ) then
  @ x   = 1
  @ max = $maxTests
else 
  @ x   = $test
  @ max = $test + 1
endif

while ( $x < $max)

  set ups  = $upsArray[$x]
  set uda  = $udaArray[$x]
  set desc = $descArray[$x]
  echo " " 
  echo "working on test:$x UPS: $ups UDA: $uda Description:$desc"
  
  rm -rf $uda.00* out.$desc.gpu out.$desc.cpu >& /dev/null
  echo "Running GPU"
  $MPIRUN sus -do_not_validate -nthreads $threads -gpu  $ups >& out.$desc.gpu
  
  echo "Running CPU"
  $MPIRUN sus -do_not_validate -nthreads $threads       $ups >& out.$desc.cpu

  echo "compare_uda -abs_tolerance $absTol -rel_tolerance $relTol -as_warnings $uda.000 $uda.001 >& out.$desc.compare"
  compare_uda -abs_tolerance $absTol -rel_tolerance $absTol -as_warnings $uda.000 $uda.001 >& out.$desc.compare
  more out.$desc.compare
  @ x = $x + 1
end

exit
