#! /bin/bash

THELIB=RadProps

source ../HelperBuildScripts/setupEnv.sh

rm -f CMakeCache.txt
rm -rf ${INSTALL_HERE}/*

cmake                                               \
  -DRadProps_ENABLE_TESTING=OFF                     \
  -DRadProps_ENABLE_PREPROCESSOR=OFF                \
                                                    \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_HERE}            \
  -DCMAKE_C_COMPILER=$CC                            \
  -DCMAKE_CXX_COMPILER=$CXX                         \
  -DCMAKE_CXX_FLAGS=-fPIC                           \
  -DTabProps_DIR=$INSTALL_BASE/TabProps/$COMP/share \
  .

if test $? == 0; then
  echo ""
  echo "Running Make..."
  echo ""
  make clean
  make -j4
  make install

  echo ""
  echo "RadProps: Updating installation permissions for ${INSTALL_HERE}..."
  chmod -R go+rX ${INSTALL_HERE}/..
fi

