#!/bin/csh -f
#__________________________________
# This script runs the orderAccuracy master script
# and emails the results to XXX
# It assumes that you've already compiled sus

if ($#argv != 1) then
  echo "usage: Nightly_Order_Accuracy < path to compiled Uintah/Standalone directory>"
  echo "Now exiting"
  exit
endif

set fresh_build = $argv

cd $fresh_build

set path = ($path $fresh_build)


#compile comparison utilities and make symbolic links to Uintah/Standalone
make uintah
make link_orderAccuracy
make compare_scalar
ln -s tools/compare_mms/compare_scalar .

if( ! -e sus || ! -e orderAccuracy) then
  echo "ERROR (Nightly_Order_Accuracy)"
  echo "Could not find either the executable sus or the orderAccuracy directory"
  echo "Now exiting"
  exit
endif

# Now run the script
echo "-------------------------------------------"
echo "Running masterScript.pl"
set path_OA = `readlink -f orderAccuracy/`
date> out
orderAccuracy/framework_scripts/masterScript.pl $path_OA >>& out

#__________________________________
# make a montage of the results
echo "__________________________________________"
echo " Now making a montage of the results"
set results = (`find order_of_accuracy -name "*.png" |sort`)

set numFigures = $#results
montage $results -geometry 640x480 -tile 1x10  montage.png

# email the results

if( -e montage.png) then
  mutt -a montage.png -s "Order of accuracy results" t.harman@utah.edu,j.thornock@utah.edu< out
else
  mutt -s "ERROR: Order of accuracy results" t.harman@utah.edu,j.thornock@utah.edu < out
endif

exit
