CC       = CC
CFLAGS   = -g -xansi -fullwarn -n32 -mips4
INCLUDES = -I..

TOP = /home/sci/data16/ddestger/Reorg
ARCHDIR = $(TOP)/irix32/SCICore
SHAREDLIB = $(CC) -shared -Wl,-no_unresolved -update_registry $(ARCHDIR)/lib/so_locations

O_DIR = $(ARCHDIR)/Persistent

OBJS = $(O_DIR)/Persistent.o $(O_DIR)/Pstreams.o
LIB = $(ARCHDIR)/lib/libPersistent.so
LIBS = -L$(ARCHDIR)/lib -lMalloc -lMultitask -lContainers -lz

all : $(LIB)

clean :
	rm $(O_DIR)/*.o $(LIB)

$(LIB): $(OBJS)
	cp $(O_DIR)/*.o .
	$(SHAREDLIB) -o $(LIB) *.o $(LIBS)
	rm *.o

$(O_DIR)/Persistent.o : Persistent.cc Persistent.h
	$(CC) $(CFLAGS) -c Persistent.cc $(INCLUDES)
	mv Persistent.o $(O_DIR)

$(O_DIR)/Pstreams.o : Pstreams.cc Pstreams.h
	$(CC) $(CFLAGS) -c Pstreams.cc $(INCLUDES)
	mv Pstreams.o $(O_DIR)

